#### What Require Inputs in this Notebook
1. [Fill in File Input](#Load-in-Data)
2. [Right or Left Hand](#Right-or-Left-Hand)
3. [Output ShotCSV](#Output-ShotCSV)
4. [Change to atNet (by Player) from tagger later](#At-Net)
5. [EDA and get Stats Here](#EDA)
6. [Output PointCSV for Visuals](#PRINT-POINTCSV-VISUALS)
7. [Output PointCSV for Upload](#Print-POINTCSV-UPLOAD)

# Table of Contents
1. [Load in Data](#Load-in-Data)
- Error Checking
- Add Columns
- [Output ShotCSV](#Output-ShotCSV)
2. [Create Point DF](#Create-Point-DF)
- Add Columns
- [Output PointCSV for Visuals](#PRINT-POINTCSV-VISUALS)
- [Output PointCSV for Upload](#Print-POINTCSV-UPLOAD)    
        - cut out points with no timestamp position    
        - atNetPlayer1 has values of the player name for display purposes instead of boolean values

# [Click for Summary Stats and EDA HERE](#EDA)

# TODO

###  Cameryn 
[Depth Count for each Point](#Add-Columns:-Depths-Count-(Short,-Deep))

[EDA for Depth of GroundStrokes](#EDA)

### Angelo 
[Change atNetPlayer to be aggregated from Coordinate Data](#Add-Column:-atNetPlayer1,-atNetPlayer2)
- atNetPlayer1 and atNetPlayer2 change to be aggreated from x and y coordinates
- Look into if isVolley column can be determined if the shotLocation and shotContact are close too each other

### (Insert Name)
[Change isApproach to be aggregatead from Coordinate Data](####-Add-Column:-isAprroach)
- see if the next consecutive shotInRally coordinates are further up into the court


### Add Error Checks
#### Add Error check to output rows where firstServeIn == NA and secondServeIn == NA AND is not a Double Falue

# Reorder csv

In [100]:
import pandas as pd
import numpy as np

In [101]:
# your_file_name = ''
# shot_data = pd.read_csv(your_file_name)

In [102]:
# # Check existing columns
# shot_data.columns

In [103]:
# desired_order = ['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
#        'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
#        'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
#        'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
#        'secondServeIn', 'secondServeZone', 'secondServeXCoord',
#        'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
#        'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
#        'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
#        'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
#        'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
#        'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
#        'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
#        'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
#        'Notes']

# shot_data = shot_data.reindex(columns=desired_order)

In [104]:

# shot_data.to_csv('Output.csv', index=False)

# Notebook Start

### Load in Data

In [105]:
import pandas as pd
import numpy as np

In [106]:
# Put your Uncleaned .csv file name here
your_file_name = 'swing_vision - swing_vision.csv'
shot_data = pd.read_csv(your_file_name)

In [107]:
# Check existing columns
shot_data.columns

Index(['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
       'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
       'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
       'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
       'secondServeIn', 'secondServeZone', 'secondServeXCoord',
       'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
       'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
       'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
       'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
       'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
       'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
       'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
       'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
       'Notes', 'isTopspin', 'isFlat', 'isKick'],
      dtype='object')

In [108]:
desired_order = ['pointScore', 'gameScore', 'setScore', 'isPointStart', 'pointStartTime',
       'isPointEnd', 'pointEndTime', 'pointNumber', 'isBreakPoint',
       'shotInRally', 'side', 'serverName', 'serverFarNear', 'firstServeIn',
       'firstServeZone', 'firstServeXCoord', 'firstServeYCoord',
       'secondServeIn', 'secondServeZone', 'secondServeXCoord',
       'secondServeYCoord', 'isAce', 'shotContactX', 'shotContactY',
       'shotDirection', 'shotFhBh', 'isSlice', 'isVolley', 'isOverhead',
       'isApproach', 'isDropshot', 'isExcitingPoint', 'atNetPlayer1',
       'atNetPlayer2', 'isLob', 'shotLocationX', 'shotLocationY', 'isWinner',
       'isErrorWideR', 'isErrorWideL', 'isErrorNet', 'isErrorLong',
       'clientTeam', 'Date', 'Division', 'Event', 'lineupPosition',
       'matchDetails', 'matchVenue', 'opponentTeam', 'player1Name',
       'player2Name', 'player1Hand', 'player2Hand', 'Round', 'Surface',
       'Notes']

shot_data = shot_data.reindex(columns=desired_order)

In [109]:
shot_data.shape[0]

588

In [110]:
shot_data.head()

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,...,matchDetails,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes
0,0-0,0-0,0-0,1.0,12000,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,Rudy Quan,Youcef Rihane,NaN,NaN,NaN,NaN,NaN
1,0-0,0-0,0-0,NaN,13000,NaN,NaN,NaN,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0-0,0-0,0-0,NaN,14000,NaN,NaN,NaN,NaN,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-0,0-0,0-0,NaN,15000,NaN,NaN,NaN,NaN,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0-0,0-0,0-0,NaN,16000,NaN,NaN,NaN,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Manually fill in meta data

In [111]:
# Fill in meta data
shot_data['clientTeam'] = 'UCLA'
shot_data['Date'] = '9/23/24'
shot_data['Division'] = 'D1'
shot_data['Event'] = 'ITA All-American Championships'
shot_data['lineupPosition'] = ''
shot_data['matchDetails'] = ''
shot_data['matchVenue'] = ''
shot_data['opponentTeam'] = 'FSU'
shot_data['player1Name'] = 'Rudy Quan'
shot_data['player2Name'] = 'Youcef Rihane'
shot_data['player1Hand'] = 'Right'
shot_data['player2Hand'] = 'Right'
shot_data['Round'] = 'Qualifying Draw R1'
shot_data['Surface'] = 'Indoor Hard'
shot_data['Notes'] = ''

### Assign Player Names

In [112]:
player1_new_name = shot_data['player1Name'].iloc[0]
player2_new_name = shot_data['player2Name'].iloc[0]

# Replace values in the serverName column
shot_data['serverName'] = shot_data['serverName'].replace({'Player1': player1_new_name, 'Player2': player2_new_name})

In [113]:
shot_data['serverName'].unique()

array(['Rudy Quan', 'Youcef Rihane', nan], dtype=object)

## Error Check 1:
#### Check that Player1Name and Player2Name have values

In [114]:
# fillInPlayer1Name = "Choose_Player1Name_Here"
# fillInPlayer2Name = "Choose_Player2Name_Here"

if shot_data.at[0, 'player1Name'] == None:
    print("player1Name was blank. Filling with 'fillInplayer1Name'")
    shot_data.at[0, 'player1Name'] = fillInPlayer1Name
else:
    print("Check Passed: player1Name is not blank. Current value:", shot_data.at[0, 'player1Name'])

# Check if player2Name is blank, if so, fill it with 'fillInplayer2Name'
if shot_data.at[0, 'player2Name'] == None:
    print("player2Name was blank. Filling with 'fillInplayer2Name'")
    shot_data.at[0, 'player2Name'] = fillInPlayer2Name
else:
    print("Check Passed: player2Name is not blank. Current value:", shot_data.at[0, 'player2Name'])

Check Passed: player1Name is not blank. Current value: Rudy Quan
Check Passed: player2Name is not blank. Current value: Youcef Rihane

## Error Check 2:
#### Check if there are missing 'Deuce' or 'Ad' sides in side column

In [115]:
# Filter out rows with 'side' values other than 'Deuce' and 'Ad'
filtered_data = shot_data[shot_data['side'].isin(['Deuce', 'Ad'])]

# Rows that don't meet the condition
rows_not_meeting_condition = shot_data[~shot_data['side'].isin(['Deuce', 'Ad'])]

# Count of rows not meeting the condition
count_rows_not_meeting_condition = len(rows_not_meeting_condition)

print("Rows with Side that aren't Deuce or Ad:", count_rows_not_meeting_condition)

# Output rows if you want to see which rows
print("Rows not meeting the condition:")
print(rows_not_meeting_condition[['pointScore', 'gameScore', 'setScore','side', 'shotInRally']])

Rows with Side that aren't Deuce or Ad: 0
Rows not meeting the condition:
Empty DataFrame
Columns: [pointScore, gameScore, setScore, side, shotInRally]
Index: []

## Error Check 3: 
#### Fills in PointNumber if not there

In [116]:
 # Check if both conditions passed
if 'pointNumber' in shot_data.columns and not shot_data['pointNumber'].isnull().any() and shot_data['pointNumber'].is_monotonic_increasing:
    print("Check Passed: Point Numbers already exist")


# Check if pointNumber exists for every row and is not empty
if 'pointNumber' not in shot_data.columns or shot_data['pointNumber'].isnull().any():
    # Execute the script to calculate pointNumber
    point_starts = (shot_data['isPointStart'] == 1)
    shot_data['pointNumber'] = point_starts.cumsum()
    
    print("Data had missing point numbers. They were filled in automatically")
    
# Check if pointNumber is in increasing order
if not shot_data['pointNumber'].is_monotonic_increasing:
    # Print the condition failure if the 'pointNumber' column is not in increasing order
    print("Data had point numbers in the wrong order. They were filled in automatically")
    point_starts = (shot_data['isPointStart'] == 1)
    shot_data['pointNumber'] = point_starts.cumsum()

Data had missing point numbers. They were filled in automatically

In [117]:
missing_pointNumber_rows = shot_data[shot_data['pointNumber'].isnull()]

# Check if there are missing rows
if len(missing_pointNumber_rows) == 0:
    print("Check Passed: All rows have pointNumber")
else:
    print(f"Count of rows missing 'pointNumber': {len(missing_pointNumber_rows)}")

Check Passed: All rows have pointNumber

## Add Column:
#### player1Hand, player2Hand

In [118]:
# fillInplayer1Hand = "Right"
# fillInplayer2Hand = "Right"

# Check if player1Hand key exists in shot_data, if not, create it
if 'player1Hand' not in shot_data:
    shot_data['player1Hand'] = None

# Check if player2Hand key exists in shot_data, if not, create it
if 'player2Hand' not in shot_data:
    shot_data['player2Hand'] = None

if shot_data.at[0, 'player1Hand'] == None:
    print("player1Hand was blank. Filling with 'fillInplayer1Hand'")
    shot_data.at[0, 'player1Hand'] = fillInplayer1Hand
else:
    print("Check Passed: player1Hand is not blank. Current value:", shot_data.at[0, 'player1Hand'])

# Check if player2Hand is blank, if so, fill it with 'fillInplayer2Hand'
if shot_data.at[0, 'player2Hand'] == None:
    print("player2Hand was blank. Filling with 'fillInplayer2Hand'")
    shot_data.at[0, 'player2Hand'] = fillInplayer2Hand
else:
    print("Check Passed: player2Hand is not blank. Current value:", shot_data.at[0, 'player2Hand'])


print("Player1Hand Current value:", shot_data.at[0, 'player1Hand'])
print("Player2Hand Current value:", shot_data.at[0, 'player2Hand'])

Check Passed: player1Hand is not blank. Current value: Right
Check Passed: player2Hand is not blank. Current value: Right
Player1Hand Current value: Right
Player2Hand Current value: Right

### Filling Columns: Forward Fill
- 'gameScore'
- 'setScore'
- 'serverName'
- 'player1Name',
- 'player2Name'
- 'player2Hand'

# Forward Fill GameScore, SetScore, tiebreakScore, serverName, player1Name, player2Name

In [119]:
columns_to_fill = ['gameScore','setScore', 'serverName', 'player1Name', 'player2Name', 'player1Hand', 'player2Hand'] 

for column in columns_to_fill:
    shot_data[column].replace(['', 'na'], pd.NaT, inplace=True)
    shot_data[column] = shot_data[column].ffill()

## Error Check 4: 
#### Check for NA's

- all 0, except missing pointScore should match amount of tiebreak shots
- side can have missing, for old tagger and not tagging side of each shot

### Fixing:
- Open CSV in __Google Sheets__ (Excel will change to date format), output game, set, point Score of missing values. Then find in google sheets, adjust, redownload, and re-upload into notebook

In [120]:
# Count empty strings in each column
empty_string_counts = (shot_data == "").sum()

# Filter out columns with zero empty strings
non_zero_counts = empty_string_counts[empty_string_counts > 0]

# Count NaN values in 'pointScore' column when 'gameScore' is '6-6'
na_tiebreak_count = shot_data.loc[shot_data['gameScore'] == '6-6', 'pointScore'].isna().sum()

side_na_count = shot_data.loc[shot_data['isPointStart'] == 1, 'side'].isna().sum()
print("\nCount of NaN values for 'side' on Point Start:", side_na_count)

# Display the count
# print("\nCount of Nan when gameScore is '6-6' (# tiebreak shots):", na_tiebreak_count)


# Count NaN or empty values in specified columns
na_counts = shot_data[[ 'pointScore', 'shotInRally', 'gameScore', 'setScore', 'side', 'serverName']].isna().sum()

# Display the counts
print(f"\nCount of NA's in these columns\n")
print(na_counts)

# Display the counts
print("\nCount of empty strings in each column that includes at least one:\n")
print(non_zero_counts)

Count of NaN values for 'side' on Point Start: 0

Count of NA's in these columns

pointScore     0
shotInRally    0
gameScore      0
setScore       0
side           0
serverName     0
dtype: int64

Count of empty strings in each column that includes at least one:

lineupPosition    588
matchDetails      588
matchVenue        588
Notes             588
dtype: int64

## Error Check 9: 
####  Outputs Missing shotInRally Rows

In [121]:
empty_shot_rows = shot_data[shot_data['shotInRally'].isnull()]

if not empty_shot_rows.empty:
    # Iterate over the index of empty_shot_rows
    for index in empty_shot_rows.index:
        # Get the row with empty shotInRally
        empty_row = shot_data.loc[index]
        
        # Get the row above it
        if index - 1 >= 0:
            above_row = shot_data.loc[index - 1]
        else:
            above_row = None
        
        # Get the row below it
        if index + 1 < len(shot_data):
            below_row = shot_data.loc[index + 1]
        else:
            below_row = None
        
        # Print the rows
        print("Empty row:")
        print(empty_row)
        print("Row above:")
        print(above_row)
        print("Row below:")
        print(below_row)
        print("====================")
else:
    print("Check Passed: No Missing shotInRally")

Check Passed: No Missing shotInRally

## Error Check 5: 
####  Check that pointNumber is increasing consecutively

- if video is bad and points are cut out, this can fail and that's ok.

In [122]:
import pandas as pd

# Assuming shot_data is a DataFrame with a 'pointNumber' column
point_numbers = shot_data['pointNumber'].unique()

# Find non-consecutive point numbers
non_consecutive = [point_numbers[i] for i in range(1, len(point_numbers)) if point_numbers[i] != point_numbers[i-1] + 1]

if not non_consecutive:
    print("Check Passed: All point numbers are consecutive.")
else:
    print("Error: Non-consecutive point numbers found.")
    # Find and output rows where the point numbers are non-consecutive
    non_consecutive_rows = shot_data[shot_data['pointNumber'].isin(non_consecutive)]
    print(non_consecutive_rows)

Check Passed: All point numbers are consecutive.

In [123]:
shot_data['pointNumber'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96])

## Error Check 6: 
#### Check same amount of start and end points

In [124]:
# Count of Point Start and Point End
num_point_start = shot_data['isPointStart'].sum()

# Count the number of rows where isPointEnd is equal to 1
num_point_end = shot_data['isPointEnd'].sum()

if num_point_start != num_point_end:
    print("Number of rows with isPointStart = 1:", num_point_start)
    print("Number of rows with isPointEnd = 1:", num_point_end)
    raise ValueError("Error: count of isPointStart = 1 and isPointEnd = 1 are not the same.")
else:
    print("Number of rows with isPointStart = 1:", num_point_start)
    print("Number of rows with isPointEnd = 1:", num_point_end)
    print('Check Passed.')

Number of rows with isPointStart = 1: 96.0
Number of rows with isPointEnd = 1: 96.0
Check Passed.

## Error Check 7: 
#### Output consecutive isPointStart with no isPointEnd, and vice versa for isPointEnd

In [125]:
# Shubhan

# Output total start, total end
# How many Points aren't enclosing between point start and point end 

# Count where isPointStart = 1
count_isPointStart = (shot_data['isPointStart'] == 1).sum()

# Count where isPointEnd = 1
count_isPointEnd = (shot_data['isPointEnd'] == 1).sum()

print("Total count where isPointStart = 1:", count_isPointStart)
print("Total count where isPointEnd = 1:", count_isPointEnd)

# Output Point/Game Scores where there is consecutive isPointStart with no isPointEnd
def check_isPointStart_in_between(shot_data):
    start_indices = shot_data.index[shot_data['isPointStart'] == 1]  # Get indices where isPointStart is True
    end_indices = shot_data.index[shot_data['isPointEnd'] == 1]  # Get indices where isPointEnd is True
    start_without_end = []

    for i in range(len(start_indices) - 1):
        current_start_index = start_indices[i]
        next_start_index = start_indices[i + 1]

        # Get all isPointEnd indices between current_start_index and next_start_index
        end_between_starts = end_indices[(end_indices >= current_start_index) & (end_indices < next_start_index)]

        # Check if there is at least one isPointEnd between current_start_index and next_start_index
        if len(end_between_starts) == 0:
            start_without_end.append(current_start_index)

    # Check the last isPointStart
    last_start_index = start_indices[-1]
    end_after_last_start = end_indices[end_indices >= last_start_index]

    if len(end_after_last_start) == 0:
        start_without_end.append(last_start_index)

    if start_without_end:
        print(" ")
        print("isPointStart without corresponding isPointEnd:")
        for index in start_without_end:
#             print("Index:", index)
#             print("pointScore:", shot_data.at[index, 'pointScore'])
#             print("gameScore:", shot_data.at[index, 'gameScore'])
#             print("setScore:", shot_data.at[index, 'setScore'])
            print(" ")
            print(shot_data.loc[start_without_end][['pointScore', 'gameScore', 'setScore', 'isPointStart']])
            print(" ")

        
        return False
    else:
        print("All isPointStart have corresponding isPointEnd.")
        return True

# Check if the condition is met
check_isPointStart_in_between(shot_data)

# Output Point/Game Scores where there is consecutive isPointEnd with no isPointStart
def check_isPointEnd_in_between(shot_data):
    start_indices = shot_data.index[shot_data['isPointStart'] == 1]  # Get indices where isPointStart is True
    end_indices = shot_data.index[shot_data['isPointEnd'] == 1]  # Get indices where isPointEnd is True
    end_without_start = []

    for i in range(len(end_indices) - 1):
        current_end_index = end_indices[i]
        next_end_index = end_indices[i + 1]

        # Get all isPointStart indices b/w current_end_index and next_end_index
        start_between_ends = start_indices[(start_indices > current_end_index) & (start_indices <= next_end_index)]

        # Check if there is at least one isPointStart between current_end_index and next_end_index
        if len(start_between_ends) == 0:
            end_without_start.append(current_end_index)

    # NOTE: This will always append the last index of the sheet because the last end will never have a corresponding start so I'm not sure if its necessary to add it to the end_without_start array
    # Check the last isPointStart
    """
    last_end_index = end_indices[-1]
    start_after_last_end = start_indices[start_indices >= last_end_index]

    if len(start_after_last_end) == 0:
        end_without_start.append(last_end_index)
    """

    if end_without_start:
        print("isPointEnd without corresponding isPointStart:")
#         for index in end_without_start:
#             print("Index:", index)
#             print("pointScore:", shot_data.at[index, 'pointScore'])
#             print("gameScore:", shot_data.at[index, 'gameScore'])
#             print("setScore:", shot_data.at[index, 'setScore'])
#             print("setScore:", shot_data.at[index, 'tiebreakScore'])

        # Output the rows of shot_data that correspond to the indices in end_without_start
        print(" ")
        print(shot_data.loc[end_without_start][['pointScore', 'gameScore', 'setScore', 'isPointEnd']])

        return False
    else:
        print("All isPointEnd have corresponding isPointStart.")
        return True

# Check if the condition is met
check_isPointEnd_in_between(shot_data)

Total count where isPointStart = 1: 96
Total count where isPointEnd = 1: 96
All isPointStart have corresponding isPointEnd.
All isPointEnd have corresponding isPointStart.

True

## Error Check 8:
#### Change the score from incorrect date format
- accounts for all variations of dates eg. (0-00-0000, 0/0/0000)

In [126]:
## Error Check 13:
#### Make Jan-00 back into 1-0 for Game/Set Score

# Make Scores Strings not Date Time
columns_to_convert = ['gameScore', 'setScore'] #if no tiebreakScore
# columns_to_convert = ['gameScore', 'setScore', 'tiebreakScore']
shot_data[columns_to_convert] = shot_data[columns_to_convert].astype(object)

In [127]:
import re

# Define a mapping for month abbreviations
month_mapping = {'Jan': '1', 'Feb': '2', 'Mar': '3', 'Apr': '4', 'May': '5', 'Jun': '6',
                 'Jul': '7', 'Aug': '8', 'Sep': '9', 'Oct': '10', 'Nov': '11', 'Dec': '12'}

# Function to convert string like 'Jan-00' to '1-0'
def convert_score_string(score_str):
    # Check if the string has a month abbreviation and a year ending with '00'
    if re.match(r'^\d{1,2}-[A-Za-z]{3}$', score_str):
        # Extract year and month abbreviation
        year, month = score_str.split('-')

        # Remove leading zeros from the year
        year = str(int(year))

        # Replace month abbreviation with corresponding number
        month_number = month_mapping.get(month, month)

        # Concatenate the parts to form the transformed string
        transformed_str = f'{year}-{month_number}'
        return transformed_str

    # Check if the string has a month abbreviation and a year with leading '0's
    elif re.match(r'^[A-Za-z]{3}-\d{1,2}$', score_str):
        # Extract month abbreviation and year
        month, year = score_str.split('-')

        # Replace month abbreviation with corresponding number
        month_number = month_mapping.get(month, month)

        # Remove leading zeros from the year
        year = str(int(year))

        # Concatenate the parts to form the transformed string
        transformed_str = f'{month_number}-{year}'
        return transformed_str

    # Check if the string has a date in the format 'month/day/year'
    elif re.match(r'^\d{1,2}/\d{1,2}/\d{4}$', score_str):
        # Extract month, day, and year
        month, day, year = score_str.split('/')

        # Remove leading zeros from month and day
        month = str(int(month))
        day = str(int(day))

        # Concatenate the parts to form the transformed string
        transformed_str = f'{month}-{day}'
        return transformed_str

    # Check if the string has a date in the format 'month-day-year'
    elif re.match(r'^\d{1,2}-\d{1,2}-\d{4}$', score_str):
        # Extract month, day, and year
        month, day, year = score_str.split('-')

        # Remove leading zeros from month and day
        month = str(int(month))
        day = str(int(day))

        # Concatenate the parts to form the transformed string
        transformed_str = f'{month}-{day}'
        return transformed_str

    return score_str

# Apply the conversion function to the relevant columns in shot_data
shot_data['gameScore'] = shot_data['gameScore'].apply(convert_score_string)
shot_data['setScore'] = shot_data['setScore'].apply(convert_score_string)
# shot_data['tiebreakerScore'] = shot_data['tiebreakerScore'].apply(convert_score_string)

## Error Check 9: 
#### Check that there is no strings in set, game scores.

In [128]:
# Assuming shot_data is your DataFrame
unique_set_scores = shot_data['setScore'].unique()
unique_game_scores = shot_data['gameScore'].unique()

# Print unique values
print("Unique Set Scores:", unique_set_scores)
print("Unique Game Scores:", unique_game_scores)

Unique Set Scores: ['0-0' '1-0']
Unique Game Scores: ['0-0' '0-1' '1-1' '2-1' '2-2' '3-2' '3-3' '4-3' '4-4' '5-4' '3-1' '4-1'
 '4-2' '5-2']

## Error Check 10 : 
### Print out all the rows where isPointStart time doesn't start in the beginning of a rally

In [129]:
# Filter the DataFrame
filtered_rows = shot_data[(shot_data['isPointStart'] == 1) & (shot_data['shotInRally'] != 1)]

# Print the filtered rows
if filtered_rows.empty:
    print ("Check passed.")
else:
    print("Rows where isPointStart = 1 and shotInRally != 1:")
    print(filtered_rows)

Check passed.

## Error Check 11: 
### Find the rows where isPointEnd = 1 and shotInRally = 1 but is neither an ace or a double fault

In [130]:
# Filter the DataFrame
filtered_rows = shot_data[
    (shot_data['isPointEnd'] == 1) & 
    (shot_data['shotInRally'] == 1) & 
    (shot_data['firstServeIn'] != 0) &
    (shot_data['secondServeIn'] != 0) &
    (shot_data['isAce'] != 1)
]

# Print the filtered rows
if filtered_rows.empty:
    print ("Check passed.")
else:
    print("Rows where isPointEnd = 1, shotInRally = 1, firstServeIn and secondServeIn are both not 0, and isAce != 1:")
    print(filtered_rows)

Check passed.

## Error Check 12: 
### Find all the rows where there are duplicate isPointStarts == 1 points
- Finds all the points where the there are the same score and isPointStart == 1
#### Warning: This will output rows that have pointScore such as "40-40", "40-A", "A-40"

In [131]:
# Filter the DataFrame
filtered_rows = shot_data[shot_data['isPointStart'] == 1]

# Output rows where isPointStart is 1 and pointScore, gameScore, and setScore have the same value
output_rows = filtered_rows[filtered_rows.duplicated(subset=['pointScore', 'gameScore', 'setScore'], keep=False)]

# Print the output rows
if output_rows.empty:
    print ("Check passed.")
else:
    print("Rows where isPointStart is 1 and pointScore, gameScore, and setScore have the same value:")
    print(output_rows[['pointScore', 'gameScore', 'setScore', 'isPointStart']])

Check passed.

## Error Check 13: 
### Find all the rows where there are duplicate isPointEnd == 1 points
- Finds all the points where the there are the same score and isPointEnd == 1

In [132]:
# Filter the DataFrame
filtered_rows = shot_data[shot_data['isPointEnd'] == 1]

# Output rows where isPointStart is 1 and pointScore, gameScore, and setScore have the same value
output_rows = filtered_rows[filtered_rows.duplicated(subset=['pointScore', 'gameScore', 'setScore'], keep=False)]

# Print the output rows
if output_rows.empty:
    print ("Check passed.")
else:
    print("Rows where isPointEnd is 1 and pointScore, gameScore, and setScore have the same value:")
    print(output_rows[['pointScore', 'gameScore', 'setScore', 'isPointStart']])

Check passed.

## Error Check 14:
### Find all the rows where there is isPointEnd == 1 but there is no isWinner, isErrorWideL, isErrorWideR, isErrorNet, isErrorLong

- Cj reccomendation: have this error check autmatically fill in how the point ends based on coordinate data

In [133]:
filtered_rows = shot_data[(shot_data['isPointEnd'] == 1) &
                          (shot_data['isWinner'] != 1) &
                          (shot_data['isErrorWideL'] != 1) &
                          (shot_data['isErrorWideR'] != 1) &
                          (shot_data['isErrorNet'] != 1) & 
                          (shot_data['isErrorLong'] != 1) &
                          (shot_data['firstServeIn'] != 0) & 
                          (shot_data['secondServeIn'] != 0)]

if filtered_rows.empty:
    print ("Check passed.")
else:
    print("Error: isPointEnd == 1 but there is no point end shot")
    print(filtered_rows[['pointScore', 'gameScore', 'setScore','isPointStart', 'isPointEnd', 'pointEndTime', 'isWinner', 'isErrorWideL', 'isErrorWideR', 'isErrorNet', 'isErrorLong']])

Check passed.

# Add More Columns

### Add Column: tiebreakScore

In [134]:
 # Check if both conditions passed
if 'tiebreakScore' in shot_data.columns and not shot_data['tiebreakScore'].isnull().any():
    print("Check Passed: tiebreakScore already exists")
else:
    shot_data['tiebreakScore'] = np.nan
    player2_new_name = shot_data['player2Name'].iloc[0]

    # Function to reverse pointScore
    def reverse_point_score(score):
        if '-' in score:
            parts = score.split('-')
            return '-'.join(parts[::-1])
        return score
    
####### CHANGED BY CJ #########
# Transfer values from pointScore to tiebreakScore where gameScore is '6-6'
shot_data.loc[shot_data['gameScore'] == '6-6', 'tiebreakScore'] = shot_data['pointScore']

# Apply reverse_point_score function where serverName is 'Player2' and tiebreakScore is not NaN
shot_data.loc[
    (shot_data['serverName'] == player2_new_name) & (shot_data['tiebreakScore'].notna()), 
    'tiebreakScore'
] = shot_data.loc[
    (shot_data['serverName'] == player2_new_name) & (shot_data['tiebreakScore'].notna()), 
    'tiebreakScore'
].apply(reverse_point_score)


####### CHANGED BY CJ (OLD) #########
    # # Apply reverse_point_score function where serverName is 'Player2'
    # shot_data.loc[shot_data['serverName'] == player2_new_name, 'pointScore'] = \
    #     shot_data.loc[shot_data['serverName'] == player2_new_name, 'pointScore'].apply(reverse_point_score)

    # # Transfer values from pointScore to tiebreakScore where gameScore is '6-6'
    # shot_data.loc[shot_data['gameScore'] == '6-6', 'tiebreakScore'] = shot_data['pointScore']

    # Set the pointScore to NaN where tiebreakScore is not NaN

shot_data.loc[pd.notna(shot_data['tiebreakScore']), 'pointScore'] = np.nan

In [135]:
shot_data.head(50)

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,...,matchVenue,opponentTeam,player1Name,player2Name,player1Hand,player2Hand,Round,Surface,Notes,tiebreakScore
0,0-0,0-0,0-0,1.0,12000,NaN,NaN,1,NaN,1,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
1,0-0,0-0,0-0,NaN,13000,NaN,NaN,1,NaN,2,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
2,0-0,0-0,0-0,NaN,14000,NaN,NaN,1,NaN,3,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
3,0-0,0-0,0-0,NaN,15000,NaN,NaN,1,NaN,4,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
4,0-0,0-0,0-0,NaN,16000,NaN,NaN,1,NaN,5,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
5,0-0,0-0,0-0,NaN,18000,NaN,NaN,1,NaN,6,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
6,0-0,0-0,0-0,NaN,19000,NaN,NaN,1,NaN,7,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
7,0-0,0-0,0-0,NaN,21000,NaN,NaN,1,NaN,8,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
8,0-0,0-0,0-0,NaN,22000,NaN,NaN,1,NaN,9,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
9,0-0,0-0,0-0,NaN,23000,NaN,NaN,1,NaN,10,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
10,0-0,0-0,0-0,NaN,25000,NaN,NaN,1,NaN,11,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
11,0-0,0-0,0-0,NaN,26000,NaN,NaN,1,NaN,12,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
12,0-0,0-0,0-0,NaN,27000,NaN,NaN,1,NaN,13,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
13,0-0,0-0,0-0,NaN,28000,NaN,NaN,1,NaN,14,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
14,0-0,0-0,0-0,NaN,29000,1.0,17000.0,1,NaN,15,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
15,0-15,0-0,0-0,1.0,56000,NaN,NaN,2,NaN,1,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
16,0-15,0-0,0-0,NaN,57000,NaN,NaN,2,NaN,2,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
17,0-15,0-0,0-0,NaN,58000,NaN,NaN,2,NaN,3,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
18,0-15,0-0,0-0,NaN,59000,NaN,NaN,2,NaN,4,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
19,0-15,0-0,0-0,NaN,61000,NaN,NaN,2,NaN,5,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
20,0-15,0-0,0-0,NaN,62000,1.0,50000.0,2,NaN,6,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
21,0-30,0-0,0-0,1.0,84000,NaN,NaN,3,NaN,1,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
22,0-30,0-0,0-0,NaN,85000,NaN,NaN,3,NaN,2,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
23,0-30,0-0,0-0,NaN,86000,NaN,NaN,3,NaN,3,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
24,0-30,0-0,0-0,NaN,88000,NaN,NaN,3,NaN,4,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
25,0-30,0-0,0-0,NaN,89000,1.0,77000.0,3,NaN,5,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
26,0-40,0-0,0-0,1.0,113000,NaN,NaN,4,1.0,1,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
27,0-40,0-0,0-0,NaN,115000,NaN,NaN,4,1.0,2,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
28,0-40,0-0,0-0,NaN,116000,NaN,NaN,4,1.0,3,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
29,0-40,0-0,0-0,NaN,117000,1.0,105000.0,4,1.0,4,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
30,15-40,0-0,0-0,1.0,138000,NaN,NaN,5,1.0,1,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
31,15-40,0-0,0-0,NaN,140000,NaN,NaN,5,1.0,2,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
32,15-40,0-0,0-0,NaN,141000,NaN,NaN,5,1.0,3,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
33,15-40,0-0,0-0,NaN,142000,1.0,130000.0,5,1.0,4,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
34,0-0,0-1,0-0,1.0,196000,NaN,NaN,6,NaN,1,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
35,0-0,0-1,0-0,NaN,196000,NaN,NaN,6,NaN,2,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
36,0-0,0-1,0-0,NaN,198000,NaN,NaN,6,NaN,3,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
37,0-0,0-1,0-0,NaN,199000,1.0,187000.0,6,NaN,4,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
38,15-0,0-1,0-0,1.0,215000,NaN,NaN,7,NaN,1,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
39,15-0,0-1,0-0,NaN,216000,NaN,NaN,7,NaN,2,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
40,15-0,0-1,0-0,NaN,218000,NaN,NaN,7,NaN,3,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
41,15-0,0-1,0-0,NaN,219000,NaN,NaN,7,NaN,4,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
42,15-0,0-1,0-0,NaN,220000,NaN,NaN,7,NaN,5,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
43,15-0,0-1,0-0,NaN,222000,NaN,NaN,7,NaN,6,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
44,15-0,0-1,0-0,NaN,223000,1.0,211000.0,7,NaN,7,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
45,15-15,0-1,0-0,1.0,254000,NaN,NaN,8,NaN,1,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
46,15-15,0-1,0-0,NaN,255000,NaN,NaN,8,NaN,2,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
47,15-15,0-1,0-0,NaN,257000,NaN,NaN,8,NaN,3,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
48,15-15,0-1,0-0,NaN,258000,NaN,NaN,8,NaN,4,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN
49,15-15,0-1,0-0,NaN,259000,NaN,NaN,8,NaN,5,...,,FSU,Rudy Quan,Youcef Rihane,Right,Right,Qualifying Draw R1,Indoor Hard,,NaN

#### Print tiebreakScore

In [136]:
shot_data.loc[shot_data['gameScore'] == '6-6', 'tiebreakScore']

Series([], Name: tiebreakScore, dtype: float64)

#### print pointScore when gameScore == '6-6'
- should be all NA

In [137]:
shot_data.loc[shot_data['gameScore'] == '6-6', 'pointScore'].head()

Series([], Name: pointScore, dtype: object)

### Add Column: returnerName

In [138]:
# Get Returner Name for Shot DF

# Extract player1Name and player2Name from the first row of shot_data
first_row_shot_df = shot_data.iloc[0]
player1_name = first_row_shot_df['player1Name']
player2_name = first_row_shot_df['player2Name']

# # Can Also Manually inpute Player 1 and 2 name
# player1_name = "Kimmi Hance"
# player2_name = "Malaika Rapolu"

def get_returner_name(server_name):
    return player2_name if server_name == player1_name else player1_name

# Add 'Returner Name' column to point_df using the function
shot_data['returnerName'] = shot_data['serverName'].apply(get_returner_name)

print(f"Player 1 = {player1_name}, Player 2 = {player2_name}")
# print(shot_data[['serverName','returnerName']])

Player 1 = Rudy Quan, Player 2 = Youcef Rihane

### Add Column: shotHitBy

In [139]:
# Add Shot Hit By for each Shot

shot_data['shotHitBy'] = shot_data.apply(lambda row: row['serverName'] if row['shotInRally'] % 2 == 1 else row['returnerName'], axis=1)
print(shot_data[['serverName', 'shotHitBy','pointNumber', 'shotInRally']].head(10))

  serverName      shotHitBy  pointNumber  shotInRally
0  Rudy Quan      Rudy Quan            1            1
1  Rudy Quan  Youcef Rihane            1            2
2  Rudy Quan      Rudy Quan            1            3
3  Rudy Quan  Youcef Rihane            1            4
4  Rudy Quan      Rudy Quan            1            5
5  Rudy Quan  Youcef Rihane            1            6
6  Rudy Quan      Rudy Quan            1            7
7  Rudy Quan  Youcef Rihane            1            8
8  Rudy Quan      Rudy Quan            1            9
9  Rudy Quan  Youcef Rihane            1           10

### Add Column: isInsideOut, isInsideIn

In [140]:
# Add columns for isInsideOut and isInsideIn, initially set to 0
shot_data['isInsideOut'] = None
shot_data['isInsideIn'] = None

# Iterate through rows
for index, row in shot_data.iterrows():
    shotHitBy = row['shotHitBy']
    player_hand = row['player1Hand'] if shotHitBy == row['player1Name'] else row['player2Hand']
    

    
    if player_hand == "Right":
        if row['side'] == "Deuce" and row['shotFhBh'] == "Backhand" and row['shotDirection'] == "Crosscourt":
            shot_data.at[index, 'isInsideOut'] = 1
        elif row['side'] == "Ad" and row['shotFhBh'] == "Forehand" and row['shotDirection'] == "Crosscourt":
            shot_data.at[index, 'isInsideOut'] = 1
        elif row['side'] == "Deuce" and row['shotFhBh'] == "Backhand" and row['shotDirection'] == "Down the Line":
            shot_data.at[index, 'isInsideIn'] = 1
        elif row['side'] == "Ad" and row['shotFhBh'] == "Forehand" and row['shotDirection'] == "Down the Line":
            shot_data.at[index, 'isInsideIn'] = 1
    elif player_hand == "Left":
        if row['side'] == "Ad" and row['shotFhBh'] == "Backhand" and row['shotDirection'] == "Crosscourt":
            shot_data.at[index, 'isInsideOut'] = 1
        elif row['side'] == "Deuce" and row['shotFhBh'] == "Forehand" and row['shotDirection'] == "Crosscourt":
            shot_data.at[index, 'isInsideOut'] = 1
        elif row['side'] == "Ad" and row['shotFhBh'] == "Backhand" and row['shotDirection'] == "Down the Line":
            shot_data.at[index, 'isInsideIn'] = 1
        elif row['side'] == "Deuce" and row['shotFhBh'] == "Forehand" and row['shotDirection'] == "Down the Line":
            shot_data.at[index, 'isInsideIn'] = 1

### Add Column: isAce

In [141]:
# Add the Ace column
shot_data['isAce'] = None

for index, row in shot_data.iterrows():
    if row['isPointEnd'] == 1:
        if row['shotInRally'] == 1: # last point is serve
            if (row['firstServeIn'] == 1 or row['secondServeIn'] == 1): # either first or second serve went in
                shot_data.at[index, 'isAce'] = 1

### Add Column: isDoubleFault

In [142]:
# Add the DoubleFault column
shot_data['isDoubleFault'] = None

for index, row in shot_data.iterrows():
    if row['isPointEnd'] == 1:
        if row['shotInRally'] == 1: # last point is serve
            if (row['firstServeIn'] != 1 and row['secondServeIn'] != 1): # either first or second serve went in
                shot_data.at[index, 'isDoubleFault'] = 1

### Add Column: pointWonBy, lastShotError

In [143]:
# Add the 'pointWonBy' column
shot_data['pointWonBy'] = None

# Add the 'lastShotError' column
shot_data['lastShotError'] = 0

for index, row in shot_data.iterrows():
    if row['isPointEnd'] == 1:
        if row['shotInRally'] == 1: # last point is serve
            if row['isAce'] == 1: 
                shot_data.at[index, 'pointWonBy'] = row['serverName']
            elif row['isDoubleFault'] == 1: 
                shot_data.at[index, 'pointWonBy'] = row['returnerName']

                
        elif row['shotInRally'] != 1:
            if row['isErrorWideR'] == 1 or row['isErrorWideL'] == 1 or row['isErrorNet'] == 1 or row['isErrorLong'] == 1: # if error
                shot_data.at[index, 'lastShotError'] = 1
                
                if row['shotInRally'] % 2 == 0:
                    shot_data.at[index, 'pointWonBy'] = row['serverName']
                else:
                    shot_data.at[index, 'pointWonBy'] = row['returnerName']
        
            elif row['isWinner'] == 1:
                if row['shotInRally'] % 2 == 0:
                    shot_data.at[index, 'pointWonBy'] = row['returnerName']
                else:
                    shot_data.at[index, 'pointWonBy'] = row['serverName']

## Error Check 15: 
#### Output Point End with no pointWonBy

In [144]:
# Missing Point End
print(shot_data[(shot_data['isPointEnd'] == 1) & (shot_data['pointWonBy'].isnull())][['pointScore', 'gameScore','setScore', 'lastShotError', 'isWinner', 'isErrorWideR', 'isErrorWideL',
       'isErrorNet', 'isErrorLong', 'pointWonBy', 'serverName', 'shotInRally']])

Empty DataFrame
Columns: [pointScore, gameScore, setScore, lastShotError, isWinner, isErrorWideR, isErrorWideL, isErrorNet, isErrorLong, pointWonBy, serverName, shotInRally]
Index: []

### Backward Fill: PointWonBy

In [145]:
shot_data['pointWonBy'].bfill()

0      Youcef Rihane
1      Youcef Rihane
2      Youcef Rihane
3      Youcef Rihane
4      Youcef Rihane
           ...
583        Rudy Quan
584        Rudy Quan
585        Rudy Quan
586        Rudy Quan
587        Rudy Quan
Name: pointWonBy, Length: 588, dtype: object

## Error Check 16: 
#### Find all rows with mismatched serve in/serve zone

In [146]:
# Find indices of all rows with firstServeIn data
first_serve_row = shot_data.index[shot_data['firstServeIn'].notnull()]
# Find indices of all rows with firstServeZone data
first_serve_placement_row = shot_data.index[shot_data['firstServeZone'].notnull()]
# Check which indices are not found in one column but are found in the other
mismatched_first_serve_rows = list(set(first_serve_row).difference(first_serve_placement_row))
# Add 2 to the indices to match numbering of Google Sheets
mismatched_first_serve_rows = [x+2 for x in mismatched_first_serve_rows]
if not mismatched_first_serve_rows:
    print("Check passed for first serves.")
else:
    print("Rows where first serve in and first serve zone are not found together: " + str(mismatched_first_serve_rows))

second_serve_row = shot_data.index[shot_data['secondServeIn'].notnull()]
second_serve_placement_row = shot_data.index[shot_data['secondServeZone'].notnull()]
mismatched_second_serve_rows = list(set(second_serve_row).difference(first_serve_placement_row))
mismatched_second_serve_rows = [x+2 for x in mismatched_second_serve_rows]
if not mismatched_second_serve_rows:
    print("Check passed for second serves.")
else:
    print("Rows where second serve in and second serve zone are not found together: " + str(mismatched_second_serve_rows))

Check passed for first serves.
Check passed for second serves.

### Add Column: serveResult, serveInPlacement

In [147]:
conditions = [
    (shot_data['isPointStart'] == 1) & (shot_data['firstServeIn'] == 1),
    (shot_data['isPointStart'] == 1) & (shot_data['firstServeIn'] != 1) & (shot_data['secondServeIn'] == 1),
    (shot_data['isPointStart'] == 1) & (shot_data['firstServeIn'] != 1) & (shot_data['secondServeIn'] != 1),]

# Define the values to be assigned for each condition
values_result = ['1st Serve In', '2nd Serve In', 'Double Fault']
values_placement = [shot_data['firstServeZone'], shot_data['secondServeZone'], shot_data['secondServeZone']]

# Use numpy.select to assign values based on conditions
shot_data['serveResult'] = np.select(conditions, values_result, default='')
shot_data['serveInPlacement'] = np.select(conditions, values_placement, default='')

# Now shot_data DataFrame is updated with serveResult and serveInPlacement values where isPointStart is 1
# print(shot_data[['serveResult', 'serveInPlacement','pointScore','side']].head(60))

In [148]:
shot_data.replace("", None, inplace=True)

In [149]:
shot_data.loc[shot_data['serveResult'] == 'Double Fault', 'serveInPlacement'].value_counts()

serveInPlacement
Body    2
Name: count, dtype: int64

### Add Column: Depth

In [150]:
def depth_metric(shotInRally, x, y, side) :
    
    if (x >= -157.5) & (x <= 157.5):
    
        if side == 'Near':
            if shotInRally % 2 == 0:
                if -455 < y < -350: return 'Deep'
                if -350 < y < 0: return 'Short'
                if y < -455: return 'Long'

            elif shotInRally % 2 == 1:
                if 455 > y > 350: return 'Deep'
                if 0 < y < 350: return 'Short'
                if y > 455: return 'Long'

        elif side == 'Far':
            if shotInRally % 2 == 1:
                if -455 < y < -350: return 'Deep'
                if -350 < y < 0: return 'Short'
                if y < -455: return 'Long'

            elif shotInRally % 2 == 0:
                if 455 > y > 350: return 'Deep'
                if 0 < y < 350: return 'Short'
                if y > 455: return 'Long'
        
shot_data['depth'] = shot_data.apply(lambda x: depth_metric(x['shotInRally'], x['shotLocationX'], x['shotLocationY'], x['serverFarNear']), axis=1)

In [151]:
shot_data[['shotInRally','serverFarNear', 'shotLocationY', 'depth']]['depth'].value_counts()

depth
Short    292
Deep      98
Long      15
Name: count, dtype: int64

In [152]:
shot_data[shot_data['depth'] == 'Long']

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,...,returnerName,shotHitBy,isInsideOut,isInsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
3,0-0,0-0,0-0,NaN,15000,NaN,NaN,1,NaN,4,...,Youcef Rihane,Youcef Rihane,None,None,None,None,0,None,None,Long
58,15-30,0-1,0-0,NaN,310000,1.0,298000.0,9,NaN,7,...,Rudy Quan,Youcef Rihane,None,1,None,Rudy Quan,1,None,None,Long
90,0-0,2-1,0-0,NaN,613000,1.0,601000.0,16,NaN,6,...,Rudy Quan,Rudy Quan,None,None,None,Youcef Rihane,1,None,None,Long
104,40-15,2-1,0-0,NaN,705000,1.0,693000.0,20,NaN,4,...,Rudy Quan,Rudy Quan,None,None,None,Youcef Rihane,1,None,None,Long
135,30-15,2-2,0-0,NaN,876000,1.0,864000.0,24,NaN,2,...,Youcef Rihane,Youcef Rihane,None,1,None,Rudy Quan,1,None,None,Long
163,0-0,3-3,0-0,NaN,1167000,NaN,NaN,31,NaN,2,...,Youcef Rihane,Youcef Rihane,None,None,None,None,0,None,None,Long
217,0-15,4-3,0-0,NaN,1484000,1.0,1472000.0,38,NaN,10,...,Rudy Quan,Rudy Quan,None,None,None,Youcef Rihane,1,None,None,Long
289,15-15,5-4,0-0,NaN,1904000,1.0,1892000.0,48,NaN,11,...,Rudy Quan,Youcef Rihane,None,None,None,Rudy Quan,1,None,None,Long
314,0-0,0-0,1-0,NaN,2143000,NaN,NaN,52,NaN,2,...,Youcef Rihane,Youcef Rihane,1,None,None,None,0,None,None,Long
319,15-0,0-0,1-0,NaN,2173000,1.0,2161000.0,53,NaN,3,...,Youcef Rihane,Rudy Quan,None,None,None,Youcef Rihane,1,None,None,Long
334,15-40,0-0,1-0,NaN,2250000,1.0,2238000.0,56,1.0,5,...,Youcef Rihane,Rudy Quan,None,1,None,Youcef Rihane,1,None,None,Long
368,0-40,0-1,1-0,NaN,2494000,NaN,NaN,61,1.0,3,...,Rudy Quan,Youcef Rihane,None,None,None,None,0,None,None,Long
421,15-15,1-1,1-0,NaN,2744000,NaN,NaN,66,NaN,3,...,Youcef Rihane,Rudy Quan,None,None,None,None,0,None,None,Long
505,30-15,3-1,1-0,NaN,3291000,1.0,3279000.0,80,NaN,8,...,Youcef Rihane,Youcef Rihane,None,None,None,Rudy Quan,1,None,None,Long
562,30-0,4-2,1-0,NaN,3759000,1.0,3747000.0,90,NaN,6,...,Youcef Rihane,Youcef Rihane,None,None,None,Rudy Quan,1,None,None,Long

In [153]:
shot_data[shot_data['isErrorLong'] == 1][['shotLocationX', 'shotLocationY']]

     shotLocationX  shotLocationY
3       107.496583     480.407037
58      135.932437    -511.711445
90      -79.044116    -488.613933
104     113.376537    -516.193274
135    -106.390469     455.887708
163     -79.583470    -496.869477
217     -66.299852    -478.467760
289      10.122671    -491.770286
314      77.875191    -475.553505
319      66.115972     508.054932
334    -127.007743     460.095669
368     -93.471703     457.004653
421     -21.282825    -510.493756
505    -113.346911    -498.941344
562     131.902652     547.043416

### Add Column: Depth

In [154]:
def depth_metric(shotInRally, x, y, side) :
    
    if (x >= -157.5) & (x <= 157.5):
    
        if side == 'Near':
            if shotInRally % 2 == 0:
                if -455 < y < -350: return 'Deep'
                if -350 < y < 0: return 'Short'
                if y < -455: return 'Long'

            elif shotInRally % 2 == 1:
                if 455 > y > 350: return 'Deep'
                if 0 < y < 350: return 'Short'
                if y > 455: return 'Long'

        elif side == 'Far':
            if shotInRally % 2 == 1:
                if -455 < y < -350: return 'Deep'
                if -350 < y < 0: return 'Short'
                if y < -455: return 'Long'

            elif shotInRally % 2 == 0:
                if 455 > y > 350: return 'Deep'
                if 0 < y < 350: return 'Short'
                if y > 455: return 'Long'
        
shot_data['depth'] = shot_data.apply(lambda x: depth_metric(x['shotInRally'], x['shotLocationX'], x['shotLocationY'], x['serverFarNear']), axis=1)

### Add Column: isAprroach

In [155]:
# NEED TO DO

### Update Column: atNetPlayer1 and atNetPlayer2

In [156]:
# Define the criteria for being at the player's net
def is_at_player_net(x, y):
    return 1 if -245 <= x <= 245 and -157.5 <= y <= 157.5 else ''

player1Name = shot_data['player1Name'].loc[0] 
player2Name = shot_data['player2Name'].loc[0]

# Apply the criteria based on the serverName
shot_data.loc[shot_data['shotHitBy'] == player1Name, 'atNetPlayer1'] = shot_data.apply(lambda row: is_at_player_net(row['shotContactX'], row['shotContactY']), axis=1)
shot_data.loc[shot_data['shotHitBy'] == player2Name, 'atNetPlayer2'] = shot_data.apply(lambda row: is_at_player_net(row['shotContactX'], row['shotContactY']), axis=1)

In [157]:
shot_data[shot_data['atNetPlayer2'] == 1]

,pointScore,gameScore,setScore,isPointStart,pointStartTime,isPointEnd,pointEndTime,pointNumber,isBreakPoint,shotInRally,...,returnerName,shotHitBy,isInsideOut,isInsideIn,isDoubleFault,pointWonBy,lastShotError,serveResult,serveInPlacement,depth
230,40-15,4-3,0-0,NaN,1566000,NaN,NaN,41,NaN,5,...,Rudy Quan,Youcef Rihane,None,None,None,None,0,None,None,Short
308,30-40,5-4,0-0,NaN,2013000,NaN,NaN,51,1.0,7,...,Rudy Quan,Youcef Rihane,1,None,None,None,0,None,None,None
310,30-40,5-4,0-0,NaN,2015000,NaN,NaN,51,1.0,9,...,Rudy Quan,Youcef Rihane,None,None,None,None,0,None,None,None
527,30-0,4-1,1-0,NaN,3598000,NaN,NaN,85,NaN,5,...,Rudy Quan,Youcef Rihane,None,None,None,None,0,None,None,Short
529,30-0,4-1,1-0,NaN,3603000,NaN,NaN,85,NaN,7,...,Rudy Quan,Youcef Rihane,None,1,None,None,0,None,None,Deep

# Double Check BEFORE Outputting

In [158]:
print(shot_data.head(10))

  pointScore gameScore setScore  isPointStart  pointStartTime  isPointEnd  \
0        0-0       0-0      0-0           1.0           12000         NaN
1        0-0       0-0      0-0           NaN           13000         NaN
2        0-0       0-0      0-0           NaN           14000         NaN
3        0-0       0-0      0-0           NaN           15000         NaN
4        0-0       0-0      0-0           NaN           16000         NaN
5        0-0       0-0      0-0           NaN           18000         NaN
6        0-0       0-0      0-0           NaN           19000         NaN
7        0-0       0-0      0-0           NaN           21000         NaN
8        0-0       0-0      0-0           NaN           22000         NaN
9        0-0       0-0      0-0           NaN           23000         NaN

   pointEndTime  pointNumber  isBreakPoint  shotInRally  ...   returnerName  \
0           NaN            1           NaN            1  ...  Youcef Rihane
1           NaN            1           NaN            2  ...  Youcef Rihane
2           NaN            1           NaN            3  ...  Youcef Rihane
3           NaN            1           NaN            4  ...  Youcef Rihane
4           NaN            1           NaN            5  ...  Youcef Rihane
5           NaN            1           NaN            6  ...  Youcef Rihane
6           NaN            1           NaN            7  ...  Youcef Rihane
7           NaN            1           NaN            8  ...  Youcef Rihane
8           NaN            1           NaN            9  ...  Youcef Rihane
9           NaN            1           NaN           10  ...  Youcef Rihane

       shotHitBy isInsideOut  isInsideIn isDoubleFault  pointWonBy  \
0      Rudy Quan        None        None          None        None
1  Youcef Rihane           1        None          None        None
2      Rudy Quan        None        None          None        None
3  Youcef Rihane        None        None          None        None
4      Rudy Quan        None        None          None        None
5  Youcef Rihane        None        None          None        None
6      Rudy Quan        None        None          None        None
7  Youcef Rihane        None        None          None        None
8      Rudy Quan        None        None          None        None
9  Youcef Rihane        None        None          None        None

   lastShotError   serveResult serveInPlacement  depth
0              0  1st Serve In                T   None
1              0          None             None  Short
2              0          None             None   Deep
3              0          None             None   Long
4              0          None             None  Short
5              0          None             None  Short
6              0          None             None  Short
7              0          None             None  Short
8              0          None             None  Short
9              0          None             None  Short

[10 rows x 68 columns]

In [159]:
print(shot_data.tail(10))

    pointScore gameScore setScore  isPointStart  pointStartTime  isPointEnd  \
578       15-0       5-2      1-0           1.0         3937000         NaN
579       15-0       5-2      1-0           NaN         3938000         NaN
580       15-0       5-2      1-0           NaN         3939000         1.0
581      15-15       5-2      1-0           1.0         3957000         NaN
582      15-15       5-2      1-0           NaN         3958000         NaN
583      15-15       5-2      1-0           NaN         3959000         1.0
584      15-30       5-2      1-0           1.0         3983000         NaN
585      15-30       5-2      1-0           NaN         3984000         NaN
586      15-30       5-2      1-0           NaN         3985000         1.0
587      15-40       5-2      1-0           1.0         3999000         1.0

     pointEndTime  pointNumber  isBreakPoint  shotInRally  ... returnerName  \
578           NaN           93           NaN            1  ...    Rudy Quan
579           NaN           93           NaN            2  ...    Rudy Quan
580     3927000.0           93           NaN            3  ...    Rudy Quan
581           NaN           94           NaN            1  ...    Rudy Quan
582           NaN           94           NaN            2  ...    Rudy Quan
583     3947000.0           94           NaN            3  ...    Rudy Quan
584           NaN           95           NaN            1  ...    Rudy Quan
585           NaN           95           NaN            2  ...    Rudy Quan
586     3973000.0           95           NaN            3  ...    Rudy Quan
587     3996000.0           96           1.0            1  ...    Rudy Quan

         shotHitBy isInsideOut  isInsideIn isDoubleFault  pointWonBy  \
578  Youcef Rihane        None        None          None        None
579      Rudy Quan        None        None          None        None
580  Youcef Rihane        None           1          None   Rudy Quan
581  Youcef Rihane        None        None          None        None
582      Rudy Quan        None           1          None        None
583  Youcef Rihane        None        None          None   Rudy Quan
584  Youcef Rihane        None        None          None        None
585      Rudy Quan        None        None          None        None
586  Youcef Rihane        None        None          None   Rudy Quan
587  Youcef Rihane        None        None             1   Rudy Quan

     lastShotError   serveResult serveInPlacement  depth
578              0  1st Serve In             Wide   None
579              0          None             None  Short
580              1          None             None   None
581              0  1st Serve In             Body   None
582              0          None             None  Short
583              1          None             None   None
584              0  1st Serve In             Body   None
585              0          None             None  Short
586              1          None             None   None
587              0  Double Fault             Body   None

[10 rows x 68 columns]

# Output ShotCSV

In [160]:
# # # Ouput Improved Shot Csv HERE
# # Assuming point_df is your DataFrame and player1Name and player2Name are the names from the first row
player1NameNoSpace = shot_data.iloc[0]['player1Name'].replace(" ", "")
player2NameNoSpace = shot_data.iloc[0]['player2Name'].replace(" ", "")

# Save DataFrame to CSV file with modified player names
shot_data.to_csv(f'Shot_Visuals_{player1NameNoSpace}_{player2NameNoSpace}.csv', index=False)

In [161]:
shot_data['pointNumber'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96])

# Below is for Point CSV

### Create Point DF

In [162]:
# Creating point_df (with only 1 row for each pointNumber)
point_df = shot_data.drop_duplicates(subset='pointNumber')[['pointNumber']]
# point_df.shape

### Add Column: player1Name, player2Name
### Set Variable: first_player1Name, first_player2Name

In [163]:
# Extract the first value of player1Name and player2Name from shot_data
first_player1Name = shot_data['player1Name'].iloc[0]
first_player2Name = shot_data['player2Name'].iloc[0]

# Fill in the first value into all rows of point_df['player1Name'] and point_df['player2Name']
point_df['player1Name'] = first_player1Name
point_df['player2Name'] = first_player2Name

### Add Column: Scores

In [164]:
point_df['pointScore'] = shot_data.groupby('pointNumber')['pointScore'].first().values
point_df['gameScore'] = shot_data.groupby('pointNumber')['gameScore'].first().values
point_df['setScore'] = shot_data.groupby('pointNumber')['setScore'].first().values
point_df['tiebreakScore'] = shot_data.groupby('pointNumber')['tiebreakScore'].first().values

### Add Column: Side

In [165]:
# Group shot_data by 'pointNumber' and get the first 'side' value for each group
side_values = shot_data.groupby('pointNumber')['side'].first().reset_index()

point_df['side'] = side_values['side'].values

### Add Column: serverName, returnerName

In [166]:
# Adds Server and Returner Names and pointScore

point_df['serverName'] = shot_data.groupby('pointNumber')['serverName'].first().values
point_df['returnerName'] = shot_data.groupby('pointNumber')['returnerName'].first().values

In [167]:
client_team_value = shot_data.loc[0, 'clientTeam']
opponent_team_value = shot_data.loc[0, 'opponentTeam']

# Adding 'clientTeam' and 'opponentTeam' columns to point_df
point_df['clientTeam'] = client_team_value
point_df['opponentTeam'] = opponent_team_value

## Warning: Will be Empty if Timestamp separate

In [168]:
# Add Start and End times per point

for index, row in shot_data.iterrows():
    point_number = row['pointNumber']
    
    if row['isPointStart'] == 1:
        point_df.loc[point_df['pointNumber'] == point_number, 'Position'] = row['pointStartTime']
    if row['isPointEnd'] == 1:
        point_df.loc[point_df['pointNumber'] == point_number, 'pointEndPosition'] = row['pointEndTime']

# Add Duration
point_df['Duration'] = point_df['pointEndPosition'] - point_df['Position']

In [169]:
len(point_df['Position'])

96

In [170]:
len(point_df['pointEndPosition'])

96

### Add Column: Rally Column
- rallyCount (x amount)
- rallyCountFreq (1-4,5-8,9-12,13+)

In [171]:
# Find the highest shotInRally for each pointNumber in shot_data
max_rally_per_point = shot_data.groupby('pointNumber')['shotInRally'].max().reset_index()
point_df['rallyCount'] = list(max_rally_per_point['shotInRally'])

# Add 'rallyCountFreq' column based on specified conditions
point_df['rallyCountFreq'] = point_df['rallyCount'].apply(lambda x: '1 - 4' if 1 <= x <= 4 else ('5 - 8' if 5 <= x <= 8 else ('9 - 12' if 9 <= x <= 12 else ('13 +' if x >= 13 else 'Error'))))

### Add Column: Serve 
- firstServeIn
- secondServeIn
- serveResult
- serveInPlacement

Part 2
- serveResult
- serveInPlacement
 
Part 3
- firstServeZone
- secondServeZone

In [172]:
# Add firstServeIn and secondServeIn

# Add firstServeIn and secondServeIn columns
point_df['firstServeIn'] = 0
point_df['secondServeIn'] = 0

for point_number in shot_data['pointNumber'].unique():
    # Check if firstServeIn is 1 for the given pointNumber in shot_data
    if any((shot_data['pointNumber'] == point_number) & (shot_data['firstServeIn'] == 1)):
        point_df.loc[point_df['pointNumber'] == point_number, 'firstServeIn'] = 1
    
    # Check if secondServeIn is 1 for the given pointNumber in shot_data
    if any((shot_data['pointNumber'] == point_number) & (shot_data['secondServeIn'] == 1)):
        point_df.loc[point_df['pointNumber'] == point_number, 'secondServeIn'] = 1

#part 2
start_points = shot_data[shot_data['isPointStart'] == 1]

# Set values in point_df to corresponding values from start_points
point_df['serveResult'] = start_points['serveResult'].values
point_df['serveInPlacement'] = start_points['serveInPlacement'].values

# part 3
serve_zones = shot_data.loc[shot_data['shotInRally'] == 1, ['pointNumber', 'firstServeZone', 'secondServeZone', 'firstServeIn', 'secondServeIn']].drop_duplicates()
point_df['firstServeZone'] = shot_data.groupby('pointNumber')['firstServeZone'].first().values
point_df['secondServeZone'] = shot_data.groupby('pointNumber')['secondServeZone'].first().values

### Add Column: Ace

In [173]:
point_df['isAce'] = ((point_df['rallyCount'] == 1) & ((point_df['serveResult'] != "Double Fault")))

# Display the resulting DataFrame
print(point_df[['pointNumber', 'rallyCount', 'isAce']].head(14))

    pointNumber  rallyCount  isAce
0             1          15  False
15            2           6  False
21            3           5  False
26            4           4  False
30            5           4  False
34            6           4  False
38            7           7  False
45            8           7  False
52            9           7  False
59           10           2  False
61           11           9  False
70           12           2  False
72           13           6  False
78           14           5  False

### Add Column: Server Coordinate Data

In [174]:
point_df['serverFarNear'] = shot_data.groupby('pointNumber')['serverFarNear'].first().values

# Add first serve X and Y column
point_df['firstServeXCoord'] = shot_data.groupby('pointNumber')['firstServeXCoord'].first().values
point_df['firstServeYCoord'] = shot_data.groupby('pointNumber')['firstServeYCoord'].first().values

# Add second serve X and Y column
point_df['secondServeXCoord'] = shot_data.groupby('pointNumber')['secondServeXCoord'].first().values
point_df['secondServeYCoord'] = shot_data.groupby('pointNumber')['secondServeYCoord'].first().values


point_df[['serverFarNear', 'firstServeXCoord', 'firstServeYCoord', 'secondServeXCoord', 'secondServeYCoord']]

,serverFarNear,firstServeXCoord,firstServeYCoord,secondServeXCoord,secondServeYCoord
0,Far,14.379320,-198.392394,NaN,NaN
15,Far,-91.154025,-230.823431,NaN,NaN
21,Far,154.477307,-228.133131,NaN,NaN
26,Far,-97.852636,-171.120833,NaN,NaN
30,Far,24.958705,-209.682841,NaN,NaN
...,...,...,...,...,...
573,Near,201.009853,-47.733011,NaN,NaN
578,Far,-136.649431,-164.693794,NaN,NaN
581,Far,95.188785,-227.321440,NaN,NaN
584,Far,-102.070970,-178.314321,NaN,NaN
587,Far,48.010783,-432.280506,76.61402,224.195746

### Add Column: Return

In [175]:
# print(shot_data[shot_data['shotInRally'] == 2][['shotDirection','shotFhBh','pointScore','gameScore','setScore']])

In [176]:
# Set the initial values of 'returnDirection' and 'returnHand' columns to None
point_df['returnDirection'] = None
point_df['returnFhBh'] = None

# Iterate through pointNumber in shot_data
for point_number in shot_data['pointNumber'].unique():
    # Check if shotInRally == 2 exists for the given pointNumber
    if 2 in shot_data.loc[shot_data['pointNumber'] == point_number, 'shotInRally'].values:
        # Get the information from the corresponding row
        row_with_return_info = shot_data[(shot_data['pointNumber'] == point_number) & (shot_data['shotInRally'] == 2)].iloc[0]

        # Assign values to 'returnDirection' and 'returnHand' columns
        point_df.loc[point_df['pointNumber'] == point_number, 'returnDirection'] = row_with_return_info['shotDirection']
        point_df.loc[point_df['pointNumber'] == point_number, 'returnFhBh'] = row_with_return_info['shotFhBh']

# Display the modified DataFrame
print(point_df.head(10))

    pointNumber player1Name    player2Name pointScore gameScore setScore  \
0             1   Rudy Quan  Youcef Rihane        0-0       0-0      0-0
15            2   Rudy Quan  Youcef Rihane       0-15       0-0      0-0
21            3   Rudy Quan  Youcef Rihane       0-30       0-0      0-0
26            4   Rudy Quan  Youcef Rihane       0-40       0-0      0-0
30            5   Rudy Quan  Youcef Rihane      15-40       0-0      0-0
34            6   Rudy Quan  Youcef Rihane        0-0       0-1      0-0
38            7   Rudy Quan  Youcef Rihane       15-0       0-1      0-0
45            8   Rudy Quan  Youcef Rihane      15-15       0-1      0-0
52            9   Rudy Quan  Youcef Rihane      15-30       0-1      0-0
59           10   Rudy Quan  Youcef Rihane      15-40       0-1      0-0

    tiebreakScore   side     serverName   returnerName  ... firstServeZone  \
0             NaN  Deuce      Rudy Quan  Youcef Rihane  ...              T
15            NaN     Ad      Rudy Quan  Youcef Rihane  ...           Body
21            NaN  Deuce      Rudy Quan  Youcef Rihane  ...           Wide
26            NaN     Ad      Rudy Quan  Youcef Rihane  ...           Body
30            NaN  Deuce      Rudy Quan  Youcef Rihane  ...              T
34            NaN  Deuce  Youcef Rihane      Rudy Quan  ...           Wide
38            NaN     Ad  Youcef Rihane      Rudy Quan  ...           Body
45            NaN  Deuce  Youcef Rihane      Rudy Quan  ...              T
52            NaN     Ad  Youcef Rihane      Rudy Quan  ...           Body
59            NaN  Deuce  Youcef Rihane      Rudy Quan  ...           Body

   secondServeZone  isAce  serverFarNear  firstServeXCoord  firstServeYCoord  \
0             None  False            Far         14.379320       -198.392394
15            None  False            Far        -91.154025       -230.823431
21            None  False            Far        154.477307       -228.133131
26            None  False            Far        -97.852636       -171.120833
30            None  False            Far         24.958705       -209.682841
34            None  False            Far        130.625864       -255.069045
38            None  False            Far        -90.943657       -190.478122
45            None  False            Far         27.490387       -164.191836
52            Wide  False            Far        -55.493564          1.242799
59            None  False            Far         55.025022       -169.492055

   secondServeXCoord  secondServeYCoord  returnDirection returnFhBh
0                NaN                NaN       Crosscourt   Backhand
15               NaN                NaN    Down the Line   Backhand
21               NaN                NaN       Crosscourt   Forehand
26               NaN                NaN       Crosscourt   Backhand
30               NaN                NaN       Crosscourt   Backhand
34               NaN                NaN    Down the Line   Forehand
38               NaN                NaN    Down the Line   Backhand
45               NaN                NaN       Crosscourt   Backhand
52       -111.856004        -151.853418       Crosscourt   Backhand
59               NaN                NaN    Down the Line   Backhand

[10 rows x 31 columns]

### Add Column: Error Column
- errorType

In [177]:
# Create an empty DataFrame to store the results
error_results = pd.DataFrame(columns=['errorType', 'pointNumber'])

# Iterate through entire shot_data
for index, row in shot_data.iterrows():
    pointNumber = row['pointNumber']
    point_error_value = None
    
    if row['isErrorWideR'] == 1:
        point_error_value = 'Wide Right'
    elif row['isErrorWideL'] == 1:
        point_error_value = 'Wide Left'
    elif 'isErrorNet' in row and row['isErrorNet'] == 1:
        point_error_value = 'Net'
    elif row['isErrorLong'] == 1:
        point_error_value = 'Long'
    

    # If an error is found, append the result to the error_results DataFrame
    if point_error_value is not None:
        error_results = pd.concat([error_results, pd.DataFrame({'pointNumber': [pointNumber], 'errorType': [point_error_value]})], ignore_index=True)


# Drop duplicates based on 'pointNumber'
error_results = error_results.drop_duplicates(subset=['pointNumber'])

In [178]:
# Create a dictionary mapping 'pointNumber' to 'errorType' in error_results
error_type_mapping = dict(zip(error_results['pointNumber'], error_results['errorType']))

# Create 'errorType' column in point_df based on the mapping
point_df['errorType'] = point_df['pointNumber'].map(error_type_mapping)

point_df = point_df.replace({np.nan: None})

### Add Column: Error (Returns)

In [179]:
def get_return_error(row):
    if row['rallyCount'] == 2:
        return row['errorType']
    else:
        return None

point_df.loc[point_df['pointNumber'] == point_number, 'serveInPlacement'] = shot_data['secondServeZone']  

# Apply the functions to create the new columns
point_df['returnError'] = point_df.apply(get_return_error, axis=1)

### Add Column: Last Shot

In [180]:
point_df['lastShotDirection'] = None
point_df['lastShotFhBh'] = None
point_df['lastShotHitBy'] = None  
point_df['lastShotResult'] = None  

# Iterate through unique pointNumbers in shot_data
for point_number in shot_data['pointNumber'].unique():
    # Check if isPointEnd == 1 exists for the given pointNumber
    if 1 in shot_data.loc[shot_data['pointNumber'] == point_number, 'isPointEnd'].values:
        # Get the information from the corresponding row
        row_with_lastshot_info = shot_data[(shot_data['pointNumber'] == point_number) & (shot_data['isPointEnd'] == 1)].iloc[0]

        # Assign values to 'lastShotDirection' and 'lastShotFhBh' columns
        point_df.loc[point_df['pointNumber'] == point_number, 'lastShotDirection'] = row_with_lastshot_info['shotDirection']
        point_df.loc[point_df['pointNumber'] == point_number, 'lastShotFhBh'] = row_with_lastshot_info['shotFhBh']
        point_df.loc[point_df['pointNumber'] == point_number, 'lastShotHitBy'] = row_with_lastshot_info['shotHitBy']
        
        # Determine lastShotResult based on conditions
        if row_with_lastshot_info['isWinner'] == 1 and not row_with_lastshot_info['isAce']:
            point_df.loc[point_df['pointNumber'] == point_number, 'lastShotResult'] = "Winner"
        elif row_with_lastshot_info['lastShotError'] == 1:
            point_df.loc[point_df['pointNumber'] == point_number, 'lastShotResult'] = "Error"

In [181]:
print(point_df['lastShotDirection'].unique())
shot_data['isPointEnd']

['Down the Line' 'Crosscourt' nan]

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
583    1.0
584    NaN
585    NaN
586    1.0
587    1.0
Name: isPointEnd, Length: 588, dtype: float64

In [182]:
shot_data[shot_data['isPointEnd'] == 1]['shotDirection'].unique()

array(['Down the Line', 'Crosscourt', nan], dtype=object)

### Add Column: pointWonBy

In [183]:
# Initialize variables to keep track of the state
prev_point_number = None
point_won_by_list = []

# Iterate through the DataFrame
for index, row in shot_data.iterrows():
    if row['isPointEnd'] == 1:
        # Check if pointNumber is different and consecutively increasing
        if prev_point_number is None or row['pointNumber'] == prev_point_number + 1:
            # Append pointWonBy to the list
            point_won_by_list.append(row['pointWonBy'])
            prev_point_number = row['pointNumber']
        else:
            raise ValueError("Error: Point numbers are not different or consecutively increasing.")
            break

# Add point_won_by_list as a new column to point_df
point_df['pointWonBy'] = point_won_by_list

### Add Column: isExcitingPoint

In [184]:
point_df['isExcitingPoint'] = shot_data.groupby('pointNumber')['isExcitingPoint'].count()

## Error Check 17: 
#### player1, player2, serverName, returnerName do not have misspellings

In [185]:
print(point_df['player1Name'].unique())
print(point_df['player2Name'].unique())
print(point_df['serverName'].unique())
print(point_df['returnerName'].unique())

if (len(point_df['serverName'].unique()) != 2):
    raise ValueError('Error: Mispelled Names')
    
if (len(point_df['returnerName'].unique()) != 2):
    raise ValueError('Error: Mispelled Names')

['Rudy Quan']
['Youcef Rihane']
['Rudy Quan' 'Youcef Rihane']
['Youcef Rihane' 'Rudy Quan']

## Error Check 18: 
#### pointWonBy has value that is not one of the two player names
- References: first_player1Name, first_player2Name from above server info in point_df

In [186]:
print(point_df['pointWonBy'].unique())
none_pointWonBy_df = point_df[~point_df['pointWonBy'].isin([first_player1Name, first_player2Name])]

if none_pointWonBy_df.empty:
    print("Check passed.")
else:
    print("Error: Rows where pointWonBy is not by either player!")
    print(none_pointWonBy_df)

['Youcef Rihane' 'Rudy Quan']
Check passed.

### Add Column: Break Point

In [187]:
break_point_values = ['0-40', '15-40', '30-40', '40-40']

# Create 'isBreakPoint' column in point_df
point_df['isBreakPoint'] = point_df['pointScore'].isin(break_point_values)

In [188]:
break_point_total = point_df['isBreakPoint'].sum()
print("Total break points:", break_point_total)
point_df[point_df['isBreakPoint'] == 1].head()

Total break points: 14

,pointNumber,player1Name,player2Name,pointScore,gameScore,setScore,tiebreakScore,side,serverName,returnerName,...,returnFhBh,errorType,returnError,lastShotDirection,lastShotFhBh,lastShotHitBy,lastShotResult,pointWonBy,isExcitingPoint,isBreakPoint
26,4,Rudy Quan,Youcef Rihane,0-40,0-0,0-0,None,Ad,Rudy Quan,Youcef Rihane,...,Backhand,Net,None,Down the Line,Backhand,Youcef Rihane,Error,Rudy Quan,0.0,True
30,5,Rudy Quan,Youcef Rihane,15-40,0-0,0-0,None,Deuce,Rudy Quan,Youcef Rihane,...,Backhand,None,None,Crosscourt,Backhand,Youcef Rihane,Winner,Youcef Rihane,0.0,True
59,10,Rudy Quan,Youcef Rihane,15-40,0-1,0-0,None,Deuce,Youcef Rihane,Rudy Quan,...,Backhand,Net,Net,Down the Line,Backhand,Rudy Quan,Error,Youcef Rihane,0.0,True
61,11,Rudy Quan,Youcef Rihane,30-40,0-1,0-0,None,Ad,Youcef Rihane,Rudy Quan,...,Backhand,Net,None,Down the Line,Forehand,Youcef Rihane,Error,Rudy Quan,0.0,True
298,50,Rudy Quan,Youcef Rihane,15-40,5-4,0-0,None,Deuce,Youcef Rihane,Rudy Quan,...,Backhand,Net,None,Down the Line,Backhand,Rudy Quan,Error,Youcef Rihane,NaN,True

### Add Columns: atNetPlayer1 and atNetPlayer2

In [ ]:
for point_number in shot_data['pointNumber'].unique():
    # Check if firstServeIn is 1 for the given pointNumber in shot_data
    if any((shot_data['pointNumber'] == point_number) & (shot_data['atNetPlayer1'] == 1)):
        point_df.loc[point_df['pointNumber'] == point_number, 'atNetPlayer1'] = 1

    # Check if secondServeIn is 1 for the given pointNumber in shot_data
    if any((shot_data['pointNumber'] == point_number) & (shot_data['atNetPlayer2'] == 1)):
        point_df.loc[point_df['pointNumber'] == point_number, 'atNetPlayer2'] = 1

# Assuming point_df is your DataFrame and player1Name is the name from the first row
player1Name = point_df.iloc[0]['player1Name']
player2Name = point_df.iloc[0]['player2Name']

# Replace values in the 'atNetPlayer1' column
point_df['atNetPlayer1'] = point_df['atNetPlayer1'].replace({0: "", 1: player1Name})
point_df['atNetPlayer2'] = point_df['atNetPlayer2'].replace({0: "", 1: player2Name})

array(['', 'Youcef Rihane'], dtype=object)

In [265]:
point_df['atNetPlayer1'].value_counts()

atNetPlayer1
             93
Rudy Quan     3
Name: count, dtype: int64

### Add Column: setNum

In [191]:
# Extract numbers from 'setScore' and calculate the sum plus 1
point_df['setNum'] = point_df['setScore'].apply(lambda x: sum(int(char) for char in x if char.isdigit()) + 1)

In [192]:
point_df.columns

Index(['pointNumber', 'player1Name', 'player2Name', 'pointScore', 'gameScore',
       'setScore', 'tiebreakScore', 'side', 'serverName', 'returnerName',
       'clientTeam', 'opponentTeam', 'Position', 'pointEndPosition',
       'Duration', 'rallyCount', 'rallyCountFreq', 'firstServeIn',
       'secondServeIn', 'serveResult', 'serveInPlacement', 'firstServeZone',
       'secondServeZone', 'isAce', 'serverFarNear', 'firstServeXCoord',
       'firstServeYCoord', 'secondServeXCoord', 'secondServeYCoord',
       'returnDirection', 'returnFhBh', 'errorType', 'returnError',
       'lastShotDirection', 'lastShotFhBh', 'lastShotHitBy', 'lastShotResult',
       'pointWonBy', 'isExcitingPoint', 'isBreakPoint', 'atNetPlayer1',
       'atNetPlayer2', 'setNum'],
      dtype='object')

### Add Column: Game Number, Set Number, Game/Set/Point for each player

In [193]:
point_df[['player1SetScore', 'player2SetScore']] = point_df['setScore'].str.split('-', expand=True)
point_df[['player1GameScore', 'player2GameScore']] = point_df['gameScore'].str.split('-', expand=True)
point_df[['player1PointScore', 'player2PointScore']] = point_df['pointScore'].str.split('-', expand=True)
if not point_df['tiebreakScore'].isnull().all() and not point_df['tiebreakScore'].eq("").all():
    # Perform the operation only when tiebreakScore is not empty
    point_df[['player1TiebreakScore', 'player2TiebreakScore']] = point_df['tiebreakScore'].str.split('-', expand=True)
else:
    # Set player1TiebreakScore and player2TiebreakScore to NaN
    point_df['player1TiebreakScore'] = np.nan
    point_df['player2TiebreakScore'] = np.nan
    
def calculate_game_number(score):
    return int(score.split('-')[0]) + int(score.split('-')[1])+1

# Apply the function to create the 'gameNumber' column
point_df['gameNumber'] = point_df['gameScore'].apply(calculate_game_number)

## Error Check 19: 
#### Output Game Number in order: Should be consecutive increasing. Ex: 1,2,3,4,5,6. End of Set 1. 1,2,3,4,5,6,7,8

In [194]:
game_numbers = point_df['gameNumber'].tolist()

# Initialize variables
seen = set()
prev = None

# Iterate through gameNumber column
for num in game_numbers:
    # If the number is not in seen or it's different from the previous one, print it
    if num not in seen or num != prev:
        print(num, end=', ')
    # If the number is the same as the previous one but not consecutive, print it
    elif num == prev and num not in seen:
        print(num, end=', ')
    # Update seen set and prev variable
    seen.add(num)
    prev = num

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8,

### Add Column: player1ServeResult

In [195]:
# Add the 'player1ServeResult' column
point_df['player1ServeResult'] = None

# Set player1ServeResult based on conditions
point_df.loc[point_df['serverName'] == point_df['player1Name'], 'player1ServeResult'] = point_df['serveResult']

In [196]:
point_df.loc[point_df['isAce'] == True, 'player1ServeResult'] = 'Ace'

### Add Column: player1ServePlacement

In [197]:
# Add the 'player1ServePlacement' column
point_df['player1ServePlacement'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['serverName'] == point_df['player1Name'], 'player1ServePlacement'] = point_df['side'] + ': ' + point_df['serveInPlacement']

### Add Column: player1ReturnPlacement

In [198]:
# Add the 'player1ReturnPlacement' column
point_df['player1ReturnPlacement'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['returnerName'] == point_df['player1Name'], 'player1ReturnPlacement'] = point_df['returnDirection']

### Add Column: player1ReturnFhBh

In [199]:
# Add the 'player1ReturnFhBh' column
point_df['player1ReturnFhBh'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['returnerName'] == point_df['player1Name'], 'player1ReturnFhBh'] = point_df['returnFhBh']

### Add Column: player1LastShotPlacement

In [200]:
# Add the 'player1LastShotFhBh' column
point_df['player1LastShotPlacement'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['lastShotHitBy'] == point_df['player1Name'], 'player1LastShotPlacement'] = point_df['lastShotDirection']

### Add Column: player1LastShotFhBh

In [201]:
# Add the 'player1LastShotFhBh' column
point_df['player1LastShotFhBh'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['lastShotHitBy'] == point_df['player1Name'], 'player1LastShotFhBh'] = point_df['lastShotFhBh']

### Add Column: player1LastShotResult

In [202]:
# Add the 'player1LastShotResult' column
point_df['player1LastShotResult'] = None

# Set player1LastShotResult based on conditions, excluding 'Ace' and 'Double Fault'
point_df.loc[
    (point_df['lastShotHitBy'] == point_df['player1Name']) & 
    ~point_df['player1ServeResult'].isin(['Ace', 'Double Fault']), 
    'player1LastShotResult'
] = point_df['lastShotResult']

In [203]:
# Add the 'player2ServeResult' column
point_df['player2ServeResult'] = None

# Set player1ServeResult based on conditions
point_df.loc[point_df['serverName'] == point_df['player2Name'], 'player2ServeResult'] = point_df['serveResult']

In [204]:
point_df.loc[point_df['isAce'] == True, 'player1ServeResult'] = 'Ace'

### Add Column: player2ServePlacement

In [205]:
# Add the 'player1ServePlacement' column
point_df['player2ServePlacement'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['serverName'] == point_df['player2Name'], 'player2ServePlacement'] = point_df['side'] + ': ' + point_df['serveInPlacement']

### Add Column: player2ReturnPlacement

In [206]:
# Add the 'player2ReturnPlacement' column
point_df['player2ReturnPlacement'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['returnerName'] == point_df['player2Name'], 'player2ReturnPlacement'] = point_df['returnDirection']

### Add Column: player2ReturnFhBh

In [207]:
# Add the 'player1ReturnFhBh' column
point_df['player2ReturnFhBh'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['returnerName'] == point_df['player2Name'], 'player2ReturnFhBh'] = point_df['returnFhBh']

### Add Column: player2LastShotPlacement

In [208]:
# Add the 'player1LastShotFhBh' column
point_df['player2LastShotPlacement'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['lastShotHitBy'] == point_df['player2Name'], 'player2LastShotPlacement'] = point_df['lastShotDirection']

### Add Column: player2LastShotFhBh

In [209]:
# Add the 'player1LastShotFhBh' column
point_df['player2LastShotFhBh'] = None

# Set player1ServePlacement based on conditions
point_df.loc[point_df['lastShotHitBy'] == point_df['player2Name'], 'player2LastShotFhBh'] = point_df['lastShotFhBh']

### Add Column: player2LastShotResult

In [210]:
# Add the 'player2LastShotResult' column
point_df['player2LastShotResult'] = None

# Set player1LastShotResult based on conditions, excluding 'Ace' and 'Double Fault'
point_df.loc[
    (point_df['lastShotHitBy'] == point_df['player2Name']) &
    ~point_df['player2ServeResult'].isin(['Ace', 'Double Fault']),
    'player2LastShotResult'
] = point_df['lastShotResult']

In [211]:
print(point_df[['setNum', 'gameScore','pointScore','player1ServePlacement','serveInPlacement']].head(10))

    setNum gameScore pointScore player1ServePlacement serveInPlacement
0        1       0-0        0-0              Deuce: T                T
15       1       0-0       0-15              Ad: Body             Body
21       1       0-0       0-30           Deuce: Wide             Wide
26       1       0-0       0-40              Ad: Body             Body
30       1       0-0      15-40              Deuce: T                T
34       1       0-1        0-0                  None             None
38       1       0-1       15-0                  None             Body
45       1       0-1      15-15                  None                T
52       1       0-1      15-30                  None             Wide
59       1       0-1      15-40                  None             Body

In [212]:
print(point_df[['setNum', 'gameScore','pointScore','player1ServePlacement','serveInPlacement']].head(10))

    setNum gameScore pointScore player1ServePlacement serveInPlacement
0        1       0-0        0-0              Deuce: T                T
15       1       0-0       0-15              Ad: Body             Body
21       1       0-0       0-30           Deuce: Wide             Wide
26       1       0-0       0-40              Ad: Body             Body
30       1       0-0      15-40              Deuce: T                T
34       1       0-1        0-0                  None             None
38       1       0-1       15-0                  None             Body
45       1       0-1      15-15                  None                T
52       1       0-1      15-30                  None             Wide
59       1       0-1      15-40                  None             Body

### Add Columns: Depths Count (Short, Deep)
#### NEED TO DO

In [213]:
# Add counts for each player on how many short and deep balls they hit in the point (group by pointNumber)
# - don't have to do long since we already know what points end with isErrorLong (and also isErrorNet)


shot_data['deep'] = np.where(shot_data['depth'] == 'Deep', 1, 0)
shot_data['short'] = np.where(shot_data['depth'] == 'Short', 1, 0)


#point_df['deepCountPlayer1'] = shot_data.groupby(['pointNumber', 'player1Name'])['deep'].sum().values
#point_df['shortCountPlayer1'] = shot_data.groupby(['pointNumber', 'player1Name'])['short'].sum().values

#point_df['deepCountPlayer2'] = shot_data.groupby(['pointNumber', 'player2Name'])['deep'].sum().values
#point_df['shortCountPlayer2'] = shot_data.groupby(['pointNumber', 'player2Name'])['short'].sum().values



### attempt 2:

deep_group = shot_data.pivot_table(index='pointNumber', columns='shotHitBy', values='deep', aggfunc='sum')
deep_group.columns = ['deepCountPlayer1', 'deepCountPlayer2']
# change NaN's from double faults to 0?
deep_group.fillna(0, inplace=True)


short_group = shot_data.pivot_table(index='pointNumber', columns='shotHitBy', values='short', aggfunc='sum')
short_group.columns = ['shortCountPlayer1', 'shortCountPlayer2']
# change NaN's from double faults to 0?
short_group.fillna(0, inplace=True)


point_df = pd.merge(point_df, deep_group, how='left', on='pointNumber')
point_df = pd.merge(point_df, short_group, how='left', on='pointNumber')

In [214]:
# # CHECK COUNTS:

# print(point_df.head(10))
# print(point_df[['shortCountPlayer1', 'shortCountPlayer2']].head(10))
# print(shot_data.head(10))

## Add Column: Name (For Video)

In [215]:
# Change pointScore to the specified format
point_df['Name'] = point_df.apply(lambda row: f"Set {row['setNum']}: {row['gameScore']}, {row['tiebreakScore']} {row['serverName']} Serving" if pd.notna(row['tiebreakScore']) else f"Set {row['setNum']}: {row['gameScore']}, {row['pointScore']} {row['serverName']} Serving", axis=1)

In [216]:
point_df[['setNum', 'gameScore','pointScore','tiebreakScore','Name']].head(5)

,setNum,gameScore,pointScore,tiebreakScore,Name
0,1,0-0,0-0,None,"Set 1: 0-0, 0-0 Rudy Quan Serving"
1,1,0-0,0-15,None,"Set 1: 0-0, 0-15 Rudy Quan Serving"
2,1,0-0,0-30,None,"Set 1: 0-0, 0-30 Rudy Quan Serving"
3,1,0-0,0-40,None,"Set 1: 0-0, 0-40 Rudy Quan Serving"
4,1,0-0,15-40,None,"Set 1: 0-0, 15-40 Rudy Quan Serving"

In [217]:
point_df[['setNum', 'gameScore','pointScore','tiebreakScore','Name']].tail(5)

,setNum,gameScore,pointScore,tiebreakScore,Name
91,2,5-2,0-0,None,"Set 2: 5-2, 0-0 Youcef Rihane Serving"
92,2,5-2,15-0,None,"Set 2: 5-2, 15-0 Youcef Rihane Serving"
93,2,5-2,15-15,None,"Set 2: 5-2, 15-15 Youcef Rihane Serving"
94,2,5-2,15-30,None,"Set 2: 5-2, 15-30 Youcef Rihane Serving"
95,2,5-2,15-40,None,"Set 2: 5-2, 15-40 Youcef Rihane Serving"

## Reorder DataFrame for Output

In [218]:
point_df_copy = point_df.copy()

In [219]:
point_df.shape

(96, 71)

In [220]:
point_df_copy.shape

(96, 71)

In [228]:
point_df.columns

Index(['Name', 'pointNumber', 'setNum', 'gameNumber', 'player1Name',
       'player2Name', 'pointScore', 'gameScore', 'setScore', 'tiebreakScore',
       'side', 'serverName', 'returnerName', 'Position', 'pointEndPosition',
       'Duration', 'pointWonBy', 'rallyCount', 'rallyCountFreq',
       'firstServeIn', 'secondServeIn', 'serveResult', 'serveInPlacement',
       'firstServeZone', 'secondServeZone', 'isAce', 'serverFarNear',
       'firstServeXCoord', 'firstServeYCoord', 'secondServeXCoord',
       'secondServeYCoord', 'returnDirection', 'returnFhBh', 'errorType',
       'returnError', 'lastShotDirection', 'lastShotFhBh', 'lastShotHitBy',
       'lastShotResult', 'isBreakPoint', 'atNetPlayer1', 'atNetPlayer2',
       'isExcitingPoint', 'player1SetScore', 'player2SetScore',
       'player1GameScore', 'player2GameScore', 'player1PointScore',
       'player2PointScore', 'player1TiebreakScore', 'player2TiebreakScore',
       'player1ServeResult', 'player1ServePlacement', 'player1ReturnPlacement',
       'player1ReturnFhBh', 'player1LastShotPlacement', 'player1LastShotFhBh',
       'player1LastShotResult', 'player2ServeResult', 'player2ServePlacement',
       'player2ReturnPlacement', 'player2ReturnFhBh',
       'player2LastShotPlacement', 'player2LastShotFhBh',
       'player2LastShotResult', 'clientTeam', 'opponentTeam'],
      dtype='object')

In [221]:
point_df.columns

Index(['pointNumber', 'player1Name', 'player2Name', 'pointScore', 'gameScore',
       'setScore', 'tiebreakScore', 'side', 'serverName', 'returnerName',
       'clientTeam', 'opponentTeam', 'Position', 'pointEndPosition',
       'Duration', 'rallyCount', 'rallyCountFreq', 'firstServeIn',
       'secondServeIn', 'serveResult', 'serveInPlacement', 'firstServeZone',
       'secondServeZone', 'isAce', 'serverFarNear', 'firstServeXCoord',
       'firstServeYCoord', 'secondServeXCoord', 'secondServeYCoord',
       'returnDirection', 'returnFhBh', 'errorType', 'returnError',
       'lastShotDirection', 'lastShotFhBh', 'lastShotHitBy', 'lastShotResult',
       'pointWonBy', 'isExcitingPoint', 'isBreakPoint', 'atNetPlayer1',
       'atNetPlayer2', 'setNum', 'player1SetScore', 'player2SetScore',
       'player1GameScore', 'player2GameScore', 'player1PointScore',
       'player2PointScore', 'player1TiebreakScore', 'player2TiebreakScore',
       'gameNumber', 'player1ServeResult', 'player1ServePlacement',
       'player1ReturnPlacement', 'player1ReturnFhBh',
       'player1LastShotPlacement', 'player1LastShotFhBh',
       'player1LastShotResult', 'player2ServeResult', 'player2ServePlacement',
       'player2ReturnPlacement', 'player2ReturnFhBh',
       'player2LastShotPlacement', 'player2LastShotFhBh',
       'player2LastShotResult', 'deepCountPlayer1', 'deepCountPlayer2',
       'shortCountPlayer1', 'shortCountPlayer2', 'Name'],
      dtype='object')

In [229]:
desired_order = [
    'Name', 'pointNumber', 'setNum', 'gameNumber', 'player1Name', 'player2Name',
    'pointScore', 'gameScore', 'setScore', 'tiebreakScore', 'side', 'serverName',
    'returnerName', 'Position', 'pointEndPosition', 'Duration', 'pointWonBy',
    'rallyCount', 'rallyCountFreq', 'firstServeIn', 'secondServeIn',
    'serveResult', 'serveInPlacement', 'firstServeZone', 'secondServeZone',
    'isAce','serverFarNear', 'firstServeXCoord', 'firstServeYCoord', 'secondServeXCoord', 'secondServeYCoord','returnDirection', 'returnFhBh', 'errorType', 'returnError',
    'lastShotDirection', 'lastShotFhBh', 'lastShotHitBy', 'lastShotResult',
    'isBreakPoint', 'atNetPlayer1', 'atNetPlayer2', 'isExcitingPoint', 'player1SetScore',
    'player2SetScore', 'player1GameScore', 'player2GameScore', 'player1PointScore',
    'player2PointScore', 'player1TiebreakScore', 'player2TiebreakScore',
    'player1ServeResult', 'player1ServePlacement', 'player1ReturnPlacement',
    'player1ReturnFhBh', 'player1LastShotPlacement', 'player1LastShotFhBh',
    'player1LastShotResult', 'player2ServeResult', 'player2ServePlacement',
       'player2ReturnPlacement', 'player2ReturnFhBh',
       'player2LastShotPlacement', 'player2LastShotFhBh',
       'player2LastShotResult', 'clientTeam', 'opponentTeam'
]

# Reorder the columns
point_df = point_df.reindex(columns=desired_order)

## Error Check 20: 
#### Check if the columns and their order are the same

In [230]:
# list1 = ['a', 'b', 'c', 'd']
# list2 = ['b', 'd', 'e']

# # Convert lists to sets
# set1 = set(point_df.columns)
# set2 = set(point_df_copy.columns)

# # Find elements in list1 but not in list2
# missing_in_list2 = set1 - set2
# print(missing_in_list2)  # {'a', 'c'}

# # Find elements in list2 but not in list1
# missing_in_list1 = set2 - set1
# print(missing_in_list1)  # {'e'}

In [231]:
len(point_df.columns)

67

In [232]:
len(point_df_copy.columns)

71

In [233]:
print(point_df.shape)
print(point_df_copy.shape)

if (point_df.shape == point_df_copy.shape):
    print('Check passed.')
else:
    raise ValueError('Error: Not the same!')

(96, 67)
(96, 71)

ValueError: Error: Not the same!

In [235]:
# Get the set of column names for each DataFrame
point_df_columns = set(point_df.columns)
point_df_copy_columns = set(point_df_copy.columns)

# Find the column names unique to each DataFrame
unique_to_point_df = point_df_columns - point_df_copy_columns
unique_to_point_df_copy = point_df_copy_columns - point_df_columns

# Output the results
if unique_to_point_df:
    print("Columns unique to point_df:", unique_to_point_df)
else:
    print("All columns in point_df are also in point_df_copy")

if unique_to_point_df_copy:
    print("Columns unique to point_df_copy:", unique_to_point_df_copy)
else:
    print("All columns in point_df_copy are also in point_df")

All columns in point_df are also in point_df_copy
Columns unique to point_df_copy: {'shortCountPlayer1', 'shortCountPlayer2', 'deepCountPlayer2', 'deepCountPlayer1'}

## Warning: All nan to ""
### Alterating Data

In [236]:
# Change Na to "" Empty String

# Assuming point_df is your DataFrame
point_df.replace([pd.NA, None, pd.NaT, float('nan')], "", inplace=True)

# Double Check before Outputting Point (FOR VISUAL)

In [242]:
point_df.head(5)

,Name,pointNumber,setNum,gameNumber,player1Name,player2Name,pointScore,gameScore,setScore,tiebreakScore,...,player1LastShotResult,player2ServeResult,player2ServePlacement,player2ReturnPlacement,player2ReturnFhBh,player2LastShotPlacement,player2LastShotFhBh,player2LastShotResult,clientTeam,opponentTeam
0,"Set 1: 0-0, 0-0 Rudy Quan Serving",1,1,1,Rudy Quan,Youcef Rihane,0-0,0-0,0-0,,...,Error,,,Crosscourt,Backhand,,,,UCLA,FSU
1,"Set 1: 0-0, 0-15 Rudy Quan Serving",2,1,1,Rudy Quan,Youcef Rihane,0-15,0-0,0-0,,...,,,,Down the Line,Backhand,Down the Line,Backhand,Winner,UCLA,FSU
2,"Set 1: 0-0, 0-30 Rudy Quan Serving",3,1,1,Rudy Quan,Youcef Rihane,0-30,0-0,0-0,,...,Error,,,Crosscourt,Forehand,,,,UCLA,FSU
3,"Set 1: 0-0, 0-40 Rudy Quan Serving",4,1,1,Rudy Quan,Youcef Rihane,0-40,0-0,0-0,,...,,,,Crosscourt,Backhand,Down the Line,Backhand,Error,UCLA,FSU
4,"Set 1: 0-0, 15-40 Rudy Quan Serving",5,1,1,Rudy Quan,Youcef Rihane,15-40,0-0,0-0,,...,,,,Crosscourt,Backhand,Crosscourt,Backhand,Winner,UCLA,FSU

In [243]:
point_df.tail(5)

,Name,pointNumber,setNum,gameNumber,player1Name,player2Name,pointScore,gameScore,setScore,tiebreakScore,...,player1LastShotResult,player2ServeResult,player2ServePlacement,player2ReturnPlacement,player2ReturnFhBh,player2LastShotPlacement,player2LastShotFhBh,player2LastShotResult,clientTeam,opponentTeam
91,"Set 2: 5-2, 0-0 Youcef Rihane Serving",92,2,8,Rudy Quan,Youcef Rihane,0-0,5-2,1-0,,...,,Double Fault,,,,Crosscourt,Forehand,,UCLA,FSU
92,"Set 2: 5-2, 15-0 Youcef Rihane Serving",93,2,8,Rudy Quan,Youcef Rihane,15-0,5-2,1-0,,...,,1st Serve In,Ad: Wide,,,Down the Line,Forehand,Error,UCLA,FSU
93,"Set 2: 5-2, 15-15 Youcef Rihane Serving",94,2,8,Rudy Quan,Youcef Rihane,15-15,5-2,1-0,,...,,1st Serve In,Deuce: Body,,,Down the Line,Backhand,Error,UCLA,FSU
94,"Set 2: 5-2, 15-30 Youcef Rihane Serving",95,2,8,Rudy Quan,Youcef Rihane,15-30,5-2,1-0,,...,,1st Serve In,Ad: Body,,,Crosscourt,Forehand,Error,UCLA,FSU
95,"Set 2: 5-2, 15-40 Youcef Rihane Serving",96,2,8,Rudy Quan,Youcef Rihane,15-40,5-2,1-0,,...,,Double Fault,Deuce: Body,,,,,,UCLA,FSU

# PRINT POINTCSV VISUALS

In [244]:
# Save point_df to CSV file

# Assuming point_df is your DataFrame and player1Name and player2Name are the names from the first row
player1NameNoSpace = point_df.iloc[0]['player1Name'].replace(" ", "")
player2NameNoSpace = point_df.iloc[0]['player2Name'].replace(" ", "")

# Save DataFrame to CSV file with modified player names
point_df.to_csv(f'Point_Visuals_{player1NameNoSpace}_{player2NameNoSpace}.csv', index=False)

In [245]:
def csv_to_json(csv_file_path, json_file_name):
    # Load CSV file into a pandas DataFrame
    df = pd.read_csv(csv_file_path)
    
    # Convert DataFrame to JSON format
    json_data = df.to_json(orient='records')
    
    # Save JSON data to a file in the same directory
    json_file_path = f'{json_file_name}'
    with open(json_file_path, 'w') as json_file:
        json_file.write(json_data)
    
    return json_file_path

# Define the CSV file path
csv_file_path = f"Point_Visuals_{player1NameNoSpace}_{player2NameNoSpace}.csv"

# Define the desired JSON file name (without extension)
json_file_name = f"Point_Visuals_{player1NameNoSpace}_{player2NameNoSpace}.json"

# Convert CSV to JSON and save in the same directory
output_file_path = csv_to_json(csv_file_path, json_file_name)

# Display the path where the JSON file is saved
output_file_path

'Point_Visuals_RudyQuan_YoucefRihane.json'

# EDA

## Shot CSV EDA

In [246]:
shot_eda = shot_data.copy()
point_df_eda = point_df.copy()

In [247]:
shot_eda = shot_data.copy()

# Can input CSV Directly here for statistics functions
## [Depth EDA]
# Filter shots for Player1:
print(f"\n\nShot Results for {first_player1Name} for match overall:")

player1_shots = shot_eda[(shot_eda['shotHitBy'] == player1Name) & (shot_eda['lastShotError'] != 1) & (shot_eda['shotInRally'] != 1)]
#player1_shots = player1_shots[player1_shots['shotInRally'] != 1]
#print(player1_shots.head(10))
num_player1_shots = len(player1_shots)
num_deep_player1_shots = player1_shots['deep'].sum()
num_short_player1_shots = player1_shots['short'].sum()

print(f"Number of Deep Shots (count): {num_deep_player1_shots}" )
print(f"Number of Short Shots (count): {num_short_player1_shots}" )

# average of ALL shots in match for Player1 (including errors/long shots but excluding serves)
print(f"Number of Deep Shots (%): {num_deep_player1_shots / num_player1_shots:.2f}%")
print(f"Number of Short Shots (%): {num_short_player1_shots / num_player1_shots:.2f}%")


# separate into forehand, backhand, slice, and volley (all sepearate from each other):
# [remove slice and volleys from fh and bh count] ??

fh_shots = player1_shots[(player1_shots['shotFhBh'] == 'Forehand')] #& (player1_shots['isSlice'] != 1) & (player1_shots['isVolley'] != 1)]
bh_shots = player1_shots[(player1_shots['shotFhBh'] == 'Backhand')] #& (player1_shots['isSlice'] != 1) & (player1_shots['isVolley'] != 1)]
slice_shots = player1_shots[player1_shots['isSlice'] == 1]
volley_shots = player1_shots[player1_shots['isVolley'] == 1]

fh_slice = player1_shots[(player1_shots['shotFhBh'] == 'Forehand') & (player1_shots['isSlice'] == 1)]
bh_slice = player1_shots[(player1_shots['shotFhBh'] == 'Backhand') & (player1_shots['isSlice'] == 1)]
fh_volley = player1_shots[(player1_shots['shotFhBh'] == 'Forehand') & (player1_shots['isVolley'] == 1)]
bh_volley = player1_shots[(player1_shots['shotFhBh'] == 'Backhand') & (player1_shots['isVolley'] == 1)]

    
print(f"\nTotal number of Forehands (count): {len(fh_shots)}" )
print(f"Forehands Deep (count): {fh_shots['deep'].sum()}" )
print(f"Forehands Short (count): {fh_shots['short'].sum()}" )
print(f"Forehands Deep (%): {( fh_shots['deep'].sum() / len(fh_shots) ):.2f}%")
print(f"Forehands Short (%): {( fh_shots['short'].sum() / len(fh_shots) ):.2f}%")


print(f"\nTotal number of Backhands (count): {len(bh_shots)}" )
print(f"Backhands Deep (count): {bh_shots['deep'].sum()}" )
print(f"Backhands Short (count): {bh_shots['short'].sum()}" )
print(f"Backhands Deep (%): {( bh_shots['deep'].sum() / len(bh_shots) ):.2f}%")
print(f"Backhands Short (%): {( bh_shots['short'].sum() / len(bh_shots) ):.2f}%")


print(f"\nTotal number of Slices (count): {len(slice_shots)}" )
print(f"Slices Deep (count): {slice_shots['deep'].sum()}" )
print(f"Slices Short (count): {slice_shots['short'].sum()}" )
print(f"Slices Deep (%): {( slice_shots['deep'].sum() / len(slice_shots) ):.2f}%")
print(f"Slices Short (%): {( slice_shots['short'].sum() / len(slice_shots) ):.2f}%")

print(f"Slices Deep Forehand(%): {(fh_slice[('deep')].sum() / len(slice_shots) ):.2f}%")
print(f"Slices Short Forehand (%): {(fh_slice[('short')].sum()/ len(slice_shots) ):.2f}%")
print(f"Slices Deep Backhand (%): {(bh_slice[('deep')].sum()/ len(slice_shots) ):.2f}")
print(f"Slices Short Backhand (%): {(bh_slice[('short')].sum()/ len(slice_shots) ):.2f}")


print(f"\nTotal number of Volleys (count): {len(volley_shots)}" )
print(f"Volleys Deep (count): {volley_shots['deep'].sum()}" )
print(f"Volleys Short (count): {volley_shots['short'].sum()}" )
print(f"Volleys Deep (%): {( volley_shots['deep'].sum() / len(volley_shots) ):.2f}%")
print(f"Volleys Short (%): {( volley_shots['short'].sum() / len(volley_shots) ):.2f}%")

print(f"Volleys Deep Forehand (%): {(fh_volley[('deep')].sum()/ len(volley_shots) ):.2f}")
print(f"Volleys Short Forehand (%): {(fh_volley[('short')].sum()/ len(volley_shots) ):.2f}")
print(f"Volleys Deep Backhand (%): {(bh_volley[('deep')].sum()/ len(volley_shots) ):.2f}")
print(f"Volleys Short Backhand (%): {(bh_volley[('short')].sum()/ len(volley_shots) ):.2f}")
# Filter shots for Player1:
print(f"\n\nShot Results for {first_player1Name} per point:")

print(f"Average Deep Shots (%): {(point_df_eda['deepCountPlayer1'].sum()) / len(point_df_eda):.2f}%")
print(f"Average Short Shots (%): {(point_df_eda['shortCountPlayer1'].sum()) / len(point_df_eda):.2f}%")


#print(point_df_eda.columns)
#point_df_eda
#player1_shots = shot_eda[shot_eda['shotHitBy'] == player1Name]

# fix above code: make avg in each point, then avg the avg?
# your_file_name = "filename.csv"
# shot_eda = pd.read_csv(your_file_name)

Shot Results for Rudy Quan for match overall:
Number of Deep Shots (count): 51
Number of Short Shots (count): 145
Number of Deep Shots (%): 0.23%
Number of Short Shots (%): 0.67%

Total number of Forehands (count): 106
Forehands Deep (count): 25
Forehands Short (count): 72
Forehands Deep (%): 0.24%
Forehands Short (%): 0.68%

Total number of Backhands (count): 112
Backhands Deep (count): 26
Backhands Short (count): 73
Backhands Deep (%): 0.23%
Backhands Short (%): 0.65%

Total number of Slices (count): 10
Slices Deep (count): 1
Slices Short (count): 6
Slices Deep (%): 0.10%
Slices Short (%): 0.60%
Slices Deep Forehand(%): 0.00%
Slices Short Forehand (%): 0.10%
Slices Deep Backhand (%): 0.10
Slices Short Backhand (%): 0.50

Total number of Volleys (count): 6
Volleys Deep (count): 0
Volleys Short (count): 3
Volleys Deep (%): 0.00%
Volleys Short (%): 0.50%
Volleys Deep Forehand (%): 0.00
Volleys Short Forehand (%): 0.33
Volleys Deep Backhand (%): 0.00
Volleys Short Backhand (%): 0.17


Shot Results for Rudy Quan per point:

KeyError: 'deepCountPlayer1'

In [ ]:
player1Name = shot_eda.iloc[0]['player1Name']

# Filter shot_data based on the conditions
approach_data_player1 = shot_eda[(shot_eda['isApproach'] == 1) & (shot_eda['shotHitBy'] == player1Name)]

# Count the distinct pointNumbers
distinct_point_numbers = approach_data_player1['pointNumber'].nunique()

# Print the result
print(f"Number of Approach Shots hit by {player1Name}: {distinct_point_numbers}" )

# print(approach_data_player1)

## Point CSV EDA

In [ ]:
# # Can input CSV Directly here for statistics functions
# import pandas as pd
# your_file_name = "Point_Visuals_Anne-ChristineLutkemeyer_SehaYu.csv"
# point_df_eda = pd.read_csv(your_file_name)

# # OR MAKE point_df_eda copy of point_df

point_df_eda = point_df.copy()

In [248]:
print(point_df_eda.columns)

Index(['Name', 'pointNumber', 'setNum', 'gameNumber', 'player1Name',
       'player2Name', 'pointScore', 'gameScore', 'setScore', 'tiebreakScore',
       'side', 'serverName', 'returnerName', 'Position', 'pointEndPosition',
       'Duration', 'pointWonBy', 'rallyCount', 'rallyCountFreq',
       'firstServeIn', 'secondServeIn', 'serveResult', 'serveInPlacement',
       'firstServeZone', 'secondServeZone', 'isAce', 'serverFarNear',
       'firstServeXCoord', 'firstServeYCoord', 'secondServeXCoord',
       'secondServeYCoord', 'returnDirection', 'returnFhBh', 'errorType',
       'returnError', 'lastShotDirection', 'lastShotFhBh', 'lastShotHitBy',
       'lastShotResult', 'isBreakPoint', 'atNetPlayer1', 'atNetPlayer2',
       'isExcitingPoint', 'player1SetScore', 'player2SetScore',
       'player1GameScore', 'player2GameScore', 'player1PointScore',
       'player2PointScore', 'player1TiebreakScore', 'player2TiebreakScore',
       'player1ServeResult', 'player1ServePlacement', 'player1ReturnPlacement',
       'player1ReturnFhBh', 'player1LastShotPlacement', 'player1LastShotFhBh',
       'player1LastShotResult', 'player2ServeResult', 'player2ServePlacement',
       'player2ReturnPlacement', 'player2ReturnFhBh',
       'player2LastShotPlacement', 'player2LastShotFhBh',
       'player2LastShotResult', 'clientTeam', 'opponentTeam'],
      dtype='object')

In [249]:
serve_in_rows = point_df_eda[(point_df_eda['serveResult'] == '1st Serve In') | (point_df_eda['serveResult'] == '2nd Serve In')]

# filter the rows where rallyCount column is equal to 1
desired_rows = serve_in_rows[serve_in_rows['rallyCount'] == 1]

# print each row
for index, row in desired_rows.iterrows():
    print(row[['pointNumber', 'setNum', 'gameNumber','serveResult','rallyCount' ,'serverName']])

pointNumber               75
setNum                     2
gameNumber                 4
serveResult     1st Serve In
rallyCount                 1
serverName     Youcef Rihane
Name: 74, dtype: object

In [250]:
first_player1Name = point_df_eda['player1Name'].iloc[0]



# Display the results
print(f"\nServe Results for {first_player1Name}:")

# Assuming point_df_eda is your DataFrame
total_serves = len(point_df_eda[point_df_eda['serverName'] == first_player1Name])
first_serve_in_count = len(point_df_eda[(point_df_eda['serverName'] == first_player1Name) & (point_df_eda['firstServeIn'] == 1)])
first_serve_won_count = len(point_df_eda[(point_df_eda['serverName'] == first_player1Name) & (point_df_eda['firstServeIn'] == 1) & (point_df_eda['pointWonBy'] == first_player1Name)])
percentage_first_serve_in = (first_serve_in_count / total_serves) * 100 if total_serves > 0 else 0
percentage_first_serve_won = (first_serve_won_count / first_serve_in_count) * 100 if first_serve_in_count > 0 else 0

second_serve_total_count = len(point_df_eda[(point_df_eda['serverName'] == first_player1Name) & (point_df_eda['firstServeIn'] == 0)])
second_serve_in_count = len(point_df_eda[(point_df_eda['serverName'] == first_player1Name) & (point_df_eda['firstServeIn'] == 0)& (point_df_eda['secondServeIn'] == 1)])
second_serve_won_count = len(point_df_eda[(point_df_eda['serverName'] == first_player1Name) & (point_df_eda['firstServeIn'] == 0)& (point_df_eda['secondServeIn'] == 1) & (point_df_eda['pointWonBy'] == first_player1Name)])
percentage_second_serve_in = (second_serve_in_count / second_serve_total_count) * 100 if second_serve_total_count > 0 else 0
percentage_second_serve_won = (second_serve_won_count / second_serve_in_count) * 100 if second_serve_in_count > 0 else 0



# Display the results
print("\nTotal Serves:", total_serves)
print("First Serve In (Count):", first_serve_in_count)
print("First Serve Won (Count):", first_serve_won_count)
print(f"First Serve In (%): {percentage_first_serve_in:.2f}%")
print(f"First Serve Won (%): {percentage_first_serve_won:.2f}%")

print("Second Serve In (Count):", second_serve_in_count)
print("Second Serve Total (Count):", second_serve_total_count)
print("Second Serve Won (Count):", second_serve_won_count)
print(f"Second Serve In (%): {percentage_second_serve_in:.2f}%")
print(f"Second Serve Won (%): {percentage_second_serve_won:.2f}%")

# Assuming point_df is your DataFrame
count_is_ace = (point_df_eda[point_df_eda['serverName'] == first_player1Name]['isAce']).sum()
count_is_double_fault = ((point_df_eda['serverName'] == first_player1Name) & (point_df_eda['serveResult'] == "Double Fault")).sum()

# Display the results
print("Ace (Count):", count_is_ace)
print("Double Fault (Count):", count_is_double_fault)

# Count of rows where serverName is equal to the first row of player1Name and pointWonBy is equal to the first row of player1Name
total_service_points_won = len(point_df_eda[(point_df_eda['serverName'] == first_player1Name) & (point_df_eda['pointWonBy'] == first_player1Name)])
total_service_points_won_percentage = total_service_points_won / total_serves *100

# Display the results
print(f"Points Won on Serve (Count) {total_service_points_won}")

print(f"Points Won on Serve (%): {total_service_points_won_percentage:.2f}%")

# Assuming point_df is your DataFrame
return_points = point_df_eda[(point_df_eda['returnerName'] == first_player1Name)] # CHANGED THIS JERRY, REMOVED RALLY COUNT >= 2

total_return = len(return_points)
returnMade = len(return_points[(return_points['rallyCount'] > 2) | ((return_points['rallyCount'] == 2) & (return_points['lastShotResult'] != 'Error'))])
returnError = len(return_points[(return_points['lastShotResult'] == 'Error') & (return_points['rallyCount'] == 2)])
returnWinner = len(return_points[(return_points['lastShotResult'] == 'Winner') & (return_points['rallyCount'] == 2)])
returnMadePercentage = returnMade/total_return

returnWonByPlayer1 = len(return_points[return_points['pointWonBy'] == first_player1Name])
returnWonByPlayer1Percentage = returnWonByPlayer1 / returnMade * 100 if returnMade > 0 else 0

deuceReturnCount = len(return_points[return_points['side'] == 'Deuce'])
adReturnCount = len(return_points[return_points['side'] == 'Ad'])


deuceReturnMade = len(return_points[(return_points['side'] == 'Deuce') & ((return_points['rallyCount'] > 2) | ((return_points['rallyCount'] == 2) & (return_points['lastShotResult'] != 'Error')))])
adReturnMade = len(return_points[(return_points['side'] == 'Ad') & ((return_points['rallyCount'] > 2) | ((return_points['rallyCount'] == 2) & (return_points['lastShotResult'] != 'Error')))])

deuceReturnMadePercentage = deuceReturnMade/deuceReturnCount
adReturnMadePercentage = adReturnMade/adReturnCount

deuceReturnWonByPlayer1 = len(return_points[(return_points['side'] == 'Deuce') & (return_points['pointWonBy'] == first_player1Name) | ((return_points['rallyCount'] == 2) & (return_points['lastShotResult'] != 'Error'))])
adReturnWonByPlayer1 = len(return_points[(return_points['side'] == 'Ad') & (return_points['pointWonBy'] == first_player1Name) | ((return_points['rallyCount'] == 2) & (return_points['lastShotResult'] != 'Error'))])

deuceReturnWonByPlayer1Percentage = deuceReturnWonByPlayer1 / deuceReturnMade * 100 if deuceReturnMade > 0 else 0
adReturnWonByPlayer1Percentage = adReturnWonByPlayer1 / adReturnMade * 100 if adReturnMade > 0 else 0




print(f"\nReturn Results for {first_player1Name}:\n")

print("Total Return (Count):", total_return)
print("Return Won (Count):", returnWonByPlayer1)
print("Return Won (%):", returnWonByPlayer1Percentage)

print("\nReturn Made (Count):", returnMade)
print("Return Made (%):", returnMadePercentage)
print("Return Error (Count):", returnError)
print("Return Winner (Count):", returnWinner)

print("\nDeuce Return (Count):", deuceReturnCount)
print("Deuce Return Made (Count):", deuceReturnMade)
print("Deuce Return Made (%):", deuceReturnMadePercentage)
print("Deuce Return Won by Player1 (%):", deuceReturnWonByPlayer1Percentage)
print("Deuce Return Won by Player1 (Count):", deuceReturnWonByPlayer1)


print("\nAd Return (Count):", adReturnCount)
print("Ad Return Made (Count):", adReturnMade)
print("Ad Return Made (%):", adReturnMadePercentage)
print("Ad Return Won by Player1 (Count):", adReturnWonByPlayer1)
print("Ad Return Won by Player1 (%):", adReturnWonByPlayer1Percentage)

# Assuming return_points is your DataFrame
deuce_return_points = return_points[(return_points['side'] == 'Deuce') & (return_points['returnerName'] == first_player1Name) & (return_points['rallyCount'] >= 2)]

# Deuce Return Points Separated by returnFhBh
deuce_forehand_return_points = deuce_return_points[deuce_return_points['returnFhBh'] == 'Forehand']
deuce_backhand_return_points = deuce_return_points[deuce_return_points['returnFhBh'] == 'Backhand']


# Count for Deuce Return Points - Made
count_deuce_forehand_made = len(deuce_forehand_return_points[(deuce_forehand_return_points['rallyCount'] > 2) | ((deuce_forehand_return_points['rallyCount'] == 2) & (deuce_forehand_return_points['lastShotResult'] != 'Error'))])
count_deuce_backhand_made = len(deuce_backhand_return_points[(deuce_backhand_return_points['rallyCount'] > 2) | ((deuce_backhand_return_points['rallyCount'] == 2) & (deuce_backhand_return_points['lastShotResult'] != 'Error'))])

# Count for Deuce Return Points - Error
count_deuce_forehand_error = len(deuce_forehand_return_points[(deuce_forehand_return_points['lastShotResult'] == 'Error') & (deuce_forehand_return_points['rallyCount'] == 2)])
count_deuce_backhand_error = len(deuce_backhand_return_points[(deuce_backhand_return_points['lastShotResult'] == 'Error') & (deuce_backhand_return_points['rallyCount'] == 2)])

# Display the counts
print("\nDeuce Forehand Return Points - Made:", count_deuce_forehand_made)
print("Deuce Forehand Return Points - Error:", count_deuce_forehand_error)

print("Deuce Backhand Return Points - Made:", count_deuce_backhand_made)
print("Deuce Backhand Return Points - Error:", count_deuce_backhand_error)

# Assuming return_points is your DataFrame
ad_return_points = return_points[(return_points['side'] == 'Ad') & (return_points['returnerName'] == first_player1Name) & (return_points['rallyCount'] >= 2)]

# Ad Return Points Separated by returnFhBh
ad_forehand_return_points = ad_return_points[ad_return_points['returnFhBh'] == 'Forehand']
ad_backhand_return_points = ad_return_points[ad_return_points['returnFhBh'] == 'Backhand']

# Count for Ad Return Points - Made
count_ad_forehand_made = len(ad_forehand_return_points[(ad_forehand_return_points['rallyCount'] > 2) | ((ad_forehand_return_points['rallyCount'] == 2) & (ad_forehand_return_points['lastShotResult'] != 'Error'))])
count_ad_backhand_made = len(ad_backhand_return_points[(ad_backhand_return_points['rallyCount'] > 2) | ((ad_backhand_return_points['rallyCount'] == 2) & (ad_backhand_return_points['lastShotResult'] != 'Error'))])

# Count for Ad Return Points - Error
count_ad_forehand_error = len(ad_forehand_return_points[(ad_forehand_return_points['lastShotResult'] == 'Error') & (ad_forehand_return_points['rallyCount'] == 2)])
count_ad_backhand_error = len(ad_backhand_return_points[(ad_backhand_return_points['lastShotResult'] == 'Error') & (ad_backhand_return_points['rallyCount'] == 2)])

# Display the counts
print("\nAd Forehand Return Points - Made:", count_ad_forehand_made)
print("Ad Forehand Return Points - Error:", count_ad_forehand_error)

print("Ad Backhand Return Points - Made:", count_ad_backhand_made)
print("Ad Backhand Return Points - Error:", count_ad_backhand_error)

print(f"\nAt Net Results for {first_player1Name}:\n")


# Total points where atNetPlayer1 = first_player1Name
total_at_net_player1 = len(point_df_eda[point_df_eda['atNetPlayer1'] == first_player1Name])

# Percentage of points where atNetPlayer1 = 1 out of total points
percentage_at_net_player1 = (total_at_net_player1 / len(point_df_eda)) * 100 if len(point_df_eda) > 0 else 0

# Display the total count and percentage of points where atNetPlayer1 = 1
print(f"Total Net Points for {first_player1Name}: {total_at_net_player1}")
print(f"Percentage of Net Points for {first_player1Name}: {percentage_at_net_player1:.2f}%")

# Points where atNetPlayer1 = first_player1Name and pointWonBy = first_player1Name
at_net_player1_and_won_by_player1 = len(point_df_eda[(point_df_eda['atNetPlayer1'] == first_player1Name) & (point_df_eda['pointWonBy'] == first_player1Name)])

# Percentage of points where atNetPlayer1 = first_player1Name and pointWonBy = first_player1Name out of total points where atNetPlayer1 = 1
percentage_at_net_player1_and_won_by_player1 = (at_net_player1_and_won_by_player1 / total_at_net_player1) * 100 if total_at_net_player1 > 0 else 0

# Display the count and percentage of points where atNetPlayer1 = 1 and pointWonBy = first_player1Name
print(f"\nTotal Net Points won by {first_player1Name}: {at_net_player1_and_won_by_player1}")
print(f"Percentage of Net Points won by {first_player1Name}: {percentage_at_net_player1_and_won_by_player1:.2f}%")

Serve Results for Rudy Quan:

Total Serves: 44
First Serve In (Count): 34
First Serve Won (Count): 19
First Serve In (%): 77.27%
First Serve Won (%): 55.88%
Second Serve In (Count): 7
Second Serve Total (Count): 10
Second Serve Won (Count): 3
Second Serve In (%): 70.00%
Second Serve Won (%): 42.86%
Ace (Count): 0
Double Fault (Count): 3
Points Won on Serve (Count) 22
Points Won on Serve (%): 50.00%

Return Results for Rudy Quan:

Total Return (Count): 52
Return Won (Count): 23
Return Won (%): 53.48837209302325

Return Made (Count): 43
Return Made (%): 0.8269230769230769
Return Error (Count): 6
Return Winner (Count): 2

Deuce Return (Count): 29
Deuce Return Made (Count): 26
Deuce Return Made (%): 0.896551724137931
Deuce Return Won by Player1 (%): 57.692307692307686
Deuce Return Won by Player1 (Count): 15

Ad Return (Count): 23
Ad Return Made (Count): 17
Ad Return Made (%): 0.7391304347826086
Ad Return Won by Player1 (Count): 10
Ad Return Won by Player1 (%): 58.82352941176471

Deuce Forehand Return Points - Made: 10
Deuce Forehand Return Points - Error: 0
Deuce Backhand Return Points - Made: 16
Deuce Backhand Return Points - Error: 2

Ad Forehand Return Points - Made: 2
Ad Forehand Return Points - Error: 0
Ad Backhand Return Points - Made: 15
Ad Backhand Return Points - Error: 4

At Net Results for Rudy Quan:

Total Net Points for Rudy Quan: 3
Percentage of Net Points for Rudy Quan: 3.12%

Total Net Points won by Rudy Quan: 3
Percentage of Net Points won by Rudy Quan: 100.00%

In [251]:
# Caitlin Breakpoint Data

# points_returned = point_df_eda[point_df_eda[]]

# print(f"\nBreakpoint Results for {first_player1Name}:\n")

# # Total points where isBreakPoint = 1
# total_breakpoint = len(point_df_eda[point_df_eda['isBreakPoint'] == 1])

# # Points where isBreakPoint = 1 and pointWonBy = first_player1Name
# breakpoint_and_won_by_player1 = len(point_df_eda[(point_df_eda['isBreakPoint'] == 1) & (point_df_eda['pointWonBy'] == first_player1Name)])

# # Percentage of points where isBreakPoint = 1 and pointWonBy = first_player1Name out of total points where isBreakPoint = 1
# percentage_breakpoint_and_won_by_player1 = (breakpoint_and_won_by_player1 / total_breakpoint) * 100 if total_breakpoint > 0 else 0

# # Display the total count of points where isBreakPoint = 1
# print(f"Total Breakpoints: {total_breakpoint}")

# # Display the count and percentage of points where isBreakPoint = 1 and pointWonBy = first_player1Name
# print(f"Total Breakpoints won by {first_player1Name}: {breakpoint_and_won_by_player1}")
# print(f"Percentage of Breakpoints won by {first_player1Name}: {percentage_breakpoint_and_won_by_player1:.2f}%")

# # Total points where isBreakPoint = 1 and serverName = first_player1Name
# total_breakpoint_serve = len(point_df_eda[(point_df_eda['isBreakPoint'] == 1) & (point_df_eda['serverName'] == first_player1Name)])

# # Points where isBreakPoint = 1, serverName = first_player1Name, and pointWonBy = first_player1Name
# breakpoint_and_won_by_player1_serve = len(point_df_eda[(point_df_eda['isBreakPoint'] == 1) & (point_df_eda['serverName'] == first_player1Name) & (point_df_eda['pointWonBy'] == first_player1Name)])

# # Percentage of points where isBreakPoint = 1, serverName = first_player1Name, and pointWonBy = first_player1Name out of total points where isBreakPoint = 1 and serverName = first_player1Name
# percentage_breakpoint_and_won_by_player1_serve = (breakpoint_and_won_by_player1_serve / total_breakpoint_serve) * 100 if total_breakpoint_serve > 0 else 0

# # Display the total count of points where isBreakPoint = 1 and serverName = first_player1Name
# print(f"\nTotal Breakpoints on Serve for {first_player1Name}: {total_breakpoint_serve}")

# # Display the count and percentage of points where isBreakPoint = 1, serverName = first_player1Name, and pointWonBy = first_player1Name
# print(f"Total Breakpoints won on Serve by {first_player1Name}: {breakpoint_and_won_by_player1_serve}")
# print(f"Percentage of Breakpoints won on Serve by {first_player1Name}: {percentage_breakpoint_and_won_by_player1_serve:.2f}%")

# Total points where isBreakPoint = 1 and returnerName = first_player1Name
total_breakpoint_return = len(point_df_eda[(point_df_eda['isBreakPoint'] == 1) & (point_df_eda['returnerName'] == first_player1Name)])

# Points where isBreakPoint = 1, returnerName = first_player1Name, and pointWonBy = first_player1Name
breakpoint_and_won_by_player1_return = len(point_df_eda[(point_df_eda['isBreakPoint'] == 1) & (point_df_eda['returnerName'] == first_player1Name) & (point_df_eda['pointWonBy'] == first_player1Name)])

# Percentage of points where isBreakPoint = 1, returnerName = first_player1Name, and pointWonBy = first_player1Name out of total points where isBreakPoint = 1 and returnerName = first_player1Name
percentage_breakpoint_and_won_by_player1_return = (breakpoint_and_won_by_player1_return / total_breakpoint_return) * 100 if total_breakpoint_return > 0 else 0

# Display the total count of points where isBreakPoint = 1 and returnerName = first_player1Name
print(f"\nTotal Breakpoints on Return for {first_player1Name}: {total_breakpoint_return}")

# Display the count and percentage of points where isBreakPoint = 1, returnerName = first_player1Name, and pointWonBy = first_player1Name
print(f"Total Breakpoints won on Return by {first_player1Name}: {breakpoint_and_won_by_player1_return}")
print(f"Percentage of Breakpoints won on Return by {first_player1Name}: {percentage_breakpoint_and_won_by_player1_return:.2f}%")

# Jimmy Returning Games Won
# games won/returning games by Jimmy Hou

points_returned = point_df_eda[point_df_eda["returnerName"] == first_player1Name]

# # Return percentage won on first serve
# first_serves_won = points_returned[(points_returned['firstServeIn'] == 1) & (points_returned['pointWonBy'] == first_player1Name)]
# total_first_serves = points_returned[points_returned['firstServeIn'] == 1]
# fs_won_per_player1 = 100 * len(first_serves_won) / len(total_first_serves)
# # print(f"\n{player1} won {fs_won_per_player1:.2f}% of first serves returned.")
# print(f"\nPerecentage of Breakpoinnts won by {first_player1Name} on Return when returning a first serve: {fs_won_per_player1:.2f}%")

# # Return percentage won on second serve
# second_serves_won = points_returned[(points_returned['secondServeIn'] == 1) & (points_returned['pointWonBy'] == first_player1Name)]
# total_second_serves = points_returned[points_returned['secondServeIn'] == 1]
# ss_won_per_player1 = 100 * len(second_serves_won) / len(total_second_serves)
# # print(f"{player1} won {ss_won_per_player1:.2f}% of second serves returned."
# print(f"Perecentage of Breakpoinnts won by {first_player1Name} on Return when returning a second serve: {ss_won_per_player1:.2f}%")

Total Breakpoints on Return for Rudy Quan: 10
Total Breakpoints won on Return by Rudy Quan: 5
Percentage of Breakpoints won on Return by Rudy Quan: 50.00%

In [252]:
point_df_eda.columns

Index(['Name', 'pointNumber', 'setNum', 'gameNumber', 'player1Name',
       'player2Name', 'pointScore', 'gameScore', 'setScore', 'tiebreakScore',
       'side', 'serverName', 'returnerName', 'Position', 'pointEndPosition',
       'Duration', 'pointWonBy', 'rallyCount', 'rallyCountFreq',
       'firstServeIn', 'secondServeIn', 'serveResult', 'serveInPlacement',
       'firstServeZone', 'secondServeZone', 'isAce', 'serverFarNear',
       'firstServeXCoord', 'firstServeYCoord', 'secondServeXCoord',
       'secondServeYCoord', 'returnDirection', 'returnFhBh', 'errorType',
       'returnError', 'lastShotDirection', 'lastShotFhBh', 'lastShotHitBy',
       'lastShotResult', 'isBreakPoint', 'atNetPlayer1', 'atNetPlayer2',
       'isExcitingPoint', 'player1SetScore', 'player2SetScore',
       'player1GameScore', 'player2GameScore', 'player1PointScore',
       'player2PointScore', 'player1TiebreakScore', 'player2TiebreakScore',
       'player1ServeResult', 'player1ServePlacement', 'player1ReturnPlacement',
       'player1ReturnFhBh', 'player1LastShotPlacement', 'player1LastShotFhBh',
       'player1LastShotResult', 'player2ServeResult', 'player2ServePlacement',
       'player2ReturnPlacement', 'player2ReturnFhBh',
       'player2LastShotPlacement', 'player2LastShotFhBh',
       'player2LastShotResult', 'clientTeam', 'opponentTeam'],
      dtype='object')

In [253]:
# Filter points where serverName is equal to first_player1Name
filtered_points = point_df[point_df['serverName'] == first_player1Name]

# Group the filtered points by player1ServePlacement and count the occurrences
serve_placement_counts = filtered_points.groupby('player1ServePlacement').size()

serve_placements_ad = serve_placement_counts.filter(like='Ad').sum()
serve_placements_deuce = serve_placement_counts.filter(like='Deuce').sum()

# Iterate over filtered_points
for index, point in filtered_points.iterrows():
    serve_placement = point['player1ServePlacement']

    # Check if serve placement is not in serve_placement_counts
    if serve_placement not in serve_placement_counts:
        print(point)


# Initialize dictionaries to store counts and percentages
point_won_counts = {}
point_won_percentages = {}
print(f"Total {len(filtered_points)}")

# Iterate over serve placements
for serve_placement, count in serve_placement_counts.items():
    # Filter points with the specific serve placement
    serve_placement_points = filtered_points[filtered_points['player1ServePlacement'] == serve_placement]
    
    # Count points won by first_player1Name
    point_won_count = serve_placement_points[serve_placement_points['pointWonBy'] == first_player1Name].shape[0]

    # Calculate percentage
    point_won_percentage = (point_won_count / count) * 100 if count > 0 else 0

    # Store counts and percentages
    point_won_counts[serve_placement] = point_won_count
    point_won_percentages[serve_placement] = point_won_percentage
    


    
    
# Filter serve placements for Ad and Deuce [CHANGED: BRIAN NTOES]
serve_placements_ad = serve_placement_counts.filter(like='Ad').sum()
serve_placements_deuce = serve_placement_counts.filter(like='Deuce').sum()    

# Print counts and percentages [CHANGED: BRIAN NOTES]
for serve_placement, count in serve_placement_counts.items():
    print(f"Serve Placement: {serve_placement}")
    print(f"Total Serves: {count}")
    
    if "Deuce" in serve_placement: # [CHANGED: BRIAN NOTES]
        deuce_serve_format_number = f"{count/serve_placements_deuce:.2f}"
        deuce_serve_percent = round(float(deuce_serve_format_number) * 100,2)
        print(f"Serve Frequency: {deuce_serve_percent}% ({count}/{serve_placements_deuce}) Deuce Serves")
    if "Ad" in serve_placement: # [CHANGED: BRIAN NOTES]
        ad_serve_format_number = f"{count/serve_placements_ad:.2f}"
        ad_serve_percent = round(float(ad_serve_format_number) * 100,2)
        print(f"Serve Frequency: {ad_serve_percent}% ({count}/{serve_placements_ad}) Ad Serves")
        
    print(f"Serves Won by {first_player1Name}: {point_won_counts.get(serve_placement, 0)}")
    print(f"Percentage: {point_won_percentages.get(serve_placement, 0):.2f}%\n")

    
# print("This is Ad count: " + str(len(point_df[(point_df['serverName'] == first_player1Name) & (point_df['side'] == 'Ad')])))
# print("This is Deuce count: " + str(len(point_df[(point_df['serverName'] == first_player1Name) & (point_df['side'] == 'Deuce')])))

Total 44
Serve Placement:
Total Serves: 3
Serves Won by Rudy Quan: 0
Percentage: 0.00%

Serve Placement: Ad: Body
Total Serves: 9
Serve Frequency: 45.0% (9/20) Ad Serves
Serves Won by Rudy Quan: 5
Percentage: 55.56%

Serve Placement: Ad: T
Total Serves: 7
Serve Frequency: 35.0% (7/20) Ad Serves
Serves Won by Rudy Quan: 3
Percentage: 42.86%

Serve Placement: Ad: Wide
Total Serves: 4
Serve Frequency: 20.0% (4/20) Ad Serves
Serves Won by Rudy Quan: 3
Percentage: 75.00%

Serve Placement: Deuce: Body
Total Serves: 6
Serve Frequency: 29.0% (6/21) Deuce Serves
Serves Won by Rudy Quan: 3
Percentage: 50.00%

Serve Placement: Deuce: T
Total Serves: 7
Serve Frequency: 33.0% (7/21) Deuce Serves
Serves Won by Rudy Quan: 4
Percentage: 57.14%

Serve Placement: Deuce: Wide
Total Serves: 8
Serve Frequency: 38.0% (8/21) Deuce Serves
Serves Won by Rudy Quan: 4
Percentage: 50.00%

In [254]:
print(f"\nError Data for {first_player1Name}:\n")
# Filter the DataFrame based on specified conditions
total_errors = point_df[(point_df['lastShotHitBy'] == first_player1Name) &
                           (point_df['lastShotResult'] == 'Error')]

import numpy as np

# Filter rows without NaN values in relevant columns
forehand_errors = point_df[(point_df['lastShotHitBy'] == first_player1Name) &
                           (point_df['lastShotResult'] == 'Error') &
                           (point_df['lastShotFhBh'] == 'Forehand') &
                           (~point_df['errorType'].isnull())]  # Ensure 'errorType' column doesn't have NaN
 
backhand_errors = point_df[(point_df['lastShotHitBy'] == first_player1Name) &
                           (point_df['lastShotResult'] == 'Error') &
                           (point_df['lastShotFhBh'] == 'Backhand') &
                           (~point_df['errorType'].isnull())]  # Ensure 'errorType' column doesn't have NaN

# Count the occurrences of 'Forehand' and 'Backhand' separately
forehand_counts = forehand_errors.shape[0]  # Count rows
backhand_counts = backhand_errors.shape[0]  # Count rows

# Print the total error counts for verification
total_error_counts = forehand_counts + backhand_counts



# Desired output order 
desired_order = ['Net', 'Long', 'Wide Right', 'Wide Left'] 

# # Get value counts of 'errorType' for Forehand errors [CHANGED: BRIAN]
# forehand_error_types = forehand_errors['errorType'].value_counts(dropna=False).loc[desired_order]  # Include NaN values in count
# forehand_error_types_df = pd.DataFrame(forehand_error_types) # change into dataframe to erase object line
# Get value counts of 'errorType' for Backhand errors



######################### CHANGED SECTION ##############################################
# [CHANGED: BRIAN]

forehand_error_types = forehand_errors['errorType'].value_counts(dropna=False)

# Create a Series with desired index containing zeros
zeros_series = pd.Series(0, index=desired_order)

# Combine the original Series with the zeros Series
forehand_error_types_combined = forehand_error_types.combine(zeros_series, max, fill_value=0)

# Reindex the Series to follow the desired order
forehand_error_types_ordered = forehand_error_types_combined.reindex(desired_order, fill_value=0)

# Create the DataFrame
forehand_error_types_df = pd.DataFrame(forehand_error_types_ordered, columns=['Count'])

# Get value counts of 'errorType' for Backhand errors [CHANGED: BRIAN]
# backhand_error_types = backhand_errors['errorType'].value_counts(dropna=False).loc[desired_order]  # Include NaN values in count
# backhand_error_types_df = pd.DataFrame(backhand_error_types) # change into dataframe to erase object line

# Get value counts of 'errorType' for Backhand errors
backhand_error_types = backhand_errors['errorType'].value_counts(dropna=False)

# Combine the original Series with the zeros Series
backhand_error_types_combined = backhand_error_types.combine(zeros_series, max, fill_value=0)

# Reindex the Series to follow the desired order
backhand_error_types_ordered = backhand_error_types_combined.reindex(desired_order, fill_value=0)

# Create the DataFrame
backhand_error_types_df = pd.DataFrame(backhand_error_types_ordered, columns=['Count'])



######################### CHANGED SECTION ##############################################


# Print the counts and error types
print("Count of Total errors:", total_error_counts)
print("Count of Forehand errors:", forehand_counts)
print(f"Forehand Error %: {(forehand_counts/total_error_counts)*100:.2f}%")
print("Count of Backhand errors:", backhand_counts)
print(f"Backhand Error %: {(backhand_counts/total_error_counts)*100:.2f}%")
print("\nForehand errors:\n", forehand_error_types_df)


# # Group by both 'lastShotDirection' and 'errorType', and then count occurrences
forehand_error_counts = forehand_errors.groupby(['player1LastShotPlacement', 'errorType']).size().unstack(fill_value=0)  # Fill NaN with 0
forehand_error_counts_ordered = forehand_error_counts.reindex(columns = desired_order) # [CHANGED: BRIAN]

print("\nValue counts of 'errorType' for Forehand errors with different directions:\n", forehand_error_counts_ordered)


print("\nBackhand errors:\n", backhand_error_types_df)


# Group by both 'lastShotDirection' and 'errorType', and then count occurrences
backhand_error_counts = backhand_errors.groupby(['player1LastShotPlacement', 'errorType']).size().unstack(fill_value=0) # Fill NaN with 0
backhand_error_counts_ordered = backhand_error_counts.reindex(columns = desired_order) # [CHANGED: BRIAN]

print("\nValue counts of 'errorType' for Backhand errors with different directions:\n", backhand_error_counts_ordered)

Error Data for Rudy Quan:

Count of Total errors: 26
Count of Forehand errors: 10
Forehand Error %: 38.46%
Count of Backhand errors: 16
Backhand Error %: 61.54%

Forehand errors:
             Count
Net             6
Long            2
Wide Right      1
Wide Left       1

Value counts of 'errorType' for Forehand errors with different directions:
 errorType                 Net  Long  Wide Right  Wide Left
player1LastShotPlacement
Crosscourt                  1     0           0          1
Down the Line               5     2           1          0

Backhand errors:
             Count
Net            11
Long            3
Wide Right      2
Wide Left       0

Value counts of 'errorType' for Backhand errors with different directions:
 errorType                 Net  Long  Wide Right  Wide Left
player1LastShotPlacement
Crosscourt                  0     2           1        NaN
Down the Line              11     1           1        NaN

# CONDENSED REPORT NEEDS UPDATE

In [255]:
pd.set_option("display.max_columns", None)
point_df.head()

,Name,pointNumber,setNum,gameNumber,player1Name,player2Name,pointScore,gameScore,setScore,tiebreakScore,side,serverName,returnerName,Position,pointEndPosition,Duration,pointWonBy,rallyCount,rallyCountFreq,firstServeIn,secondServeIn,serveResult,serveInPlacement,firstServeZone,secondServeZone,isAce,serverFarNear,firstServeXCoord,firstServeYCoord,secondServeXCoord,secondServeYCoord,returnDirection,returnFhBh,errorType,returnError,lastShotDirection,lastShotFhBh,lastShotHitBy,lastShotResult,isBreakPoint,atNetPlayer1,atNetPlayer2,isExcitingPoint,player1SetScore,player2SetScore,player1GameScore,player2GameScore,player1PointScore,player2PointScore,player1TiebreakScore,player2TiebreakScore,player1ServeResult,player1ServePlacement,player1ReturnPlacement,player1ReturnFhBh,player1LastShotPlacement,player1LastShotFhBh,player1LastShotResult,player2ServeResult,player2ServePlacement,player2ReturnPlacement,player2ReturnFhBh,player2LastShotPlacement,player2LastShotFhBh,player2LastShotResult,clientTeam,opponentTeam
0,"Set 1: 0-0, 0-0 Rudy Quan Serving",1,1,1,Rudy Quan,Youcef Rihane,0-0,0-0,0-0,,Deuce,Rudy Quan,Youcef Rihane,12000.0,17000.0,5000.0,Youcef Rihane,15,13 +,1,0,1st Serve In,T,T,,False,Far,14.379320,-198.392394,,,Crosscourt,Backhand,Long,,Down the Line,Forehand,Rudy Quan,Error,False,,,,0,0,0,0,0,0,,,1st Serve In,Deuce: T,,,Down the Line,Forehand,Error,,,Crosscourt,Backhand,,,,UCLA,FSU
1,"Set 1: 0-0, 0-15 Rudy Quan Serving",2,1,1,Rudy Quan,Youcef Rihane,0-15,0-0,0-0,,Ad,Rudy Quan,Youcef Rihane,56000.0,50000.0,-6000.0,Youcef Rihane,6,5 - 8,1,0,1st Serve In,Body,Body,,False,Far,-91.154025,-230.823431,,,Down the Line,Backhand,,,Down the Line,Backhand,Youcef Rihane,Winner,False,,,0.0,0,0,0,0,0,15,,,1st Serve In,Ad: Body,,,,,,,,Down the Line,Backhand,Down the Line,Backhand,Winner,UCLA,FSU
2,"Set 1: 0-0, 0-30 Rudy Quan Serving",3,1,1,Rudy Quan,Youcef Rihane,0-30,0-0,0-0,,Deuce,Rudy Quan,Youcef Rihane,84000.0,77000.0,-7000.0,Youcef Rihane,5,5 - 8,1,0,1st Serve In,Wide,Wide,,False,Far,154.477307,-228.133131,,,Crosscourt,Forehand,Net,,Down the Line,Backhand,Rudy Quan,Error,False,,,0.0,0,0,0,0,0,30,,,1st Serve In,Deuce: Wide,,,Down the Line,Backhand,Error,,,Crosscourt,Forehand,,,,UCLA,FSU
3,"Set 1: 0-0, 0-40 Rudy Quan Serving",4,1,1,Rudy Quan,Youcef Rihane,0-40,0-0,0-0,,Ad,Rudy Quan,Youcef Rihane,113000.0,105000.0,-8000.0,Rudy Quan,4,1 - 4,1,0,1st Serve In,Body,Body,,False,Far,-97.852636,-171.120833,,,Crosscourt,Backhand,Net,,Down the Line,Backhand,Youcef Rihane,Error,True,,,0.0,0,0,0,0,0,40,,,1st Serve In,Ad: Body,,,,,,,,Crosscourt,Backhand,Down the Line,Backhand,Error,UCLA,FSU
4,"Set 1: 0-0, 15-40 Rudy Quan Serving",5,1,1,Rudy Quan,Youcef Rihane,15-40,0-0,0-0,,Deuce,Rudy Quan,Youcef Rihane,138000.0,130000.0,-8000.0,Youcef Rihane,4,1 - 4,1,0,1st Serve In,T,T,,False,Far,24.958705,-209.682841,,,Crosscourt,Backhand,,,Crosscourt,Backhand,Youcef Rihane,Winner,True,,,0.0,0,0,0,0,15,40,,,1st Serve In,Deuce: T,,,,,,,,Crosscourt,Backhand,Crosscourt,Backhand,Winner,UCLA,FSU

### Using FPDF package

In [256]:
from fpdf import FPDF
import pandas as pd
import os

### Needed Variables

In [258]:
# Variables that will be passed into the code (Replace these with your actual dataset values)
player_name = point_df['player1Name'].iloc[0]
opponent_name = point_df['player2Name'].iloc[0]
client_team = point_df['clientTeam'].iloc[0]
opponent_team = point_df['opponentTeam'].iloc[0]

set_list = point_df['setNum'].unique()
set_list[1]

current_set = point_df[point_df['setNum'] == 1]
last_index = len(current_set) - 1
game_score = point_df.iloc[last_index]['gameScore']

player_game = game_score.split("-")[0]
opponent_game = game_score.split("-")[1]

# if '5' in game_score:
#     if '5-' in game_score:

# point_df.iloc[52]['setScore']

# for i in point_df['setNum'].unique():
#     current_set = point_df[point_df['setNum'] == i]
#     last_index = len(current_set) - 1
#     game_score = point_df.iloc[last_index]['gameScore']

### Create PDF

In [259]:
# Create PDF
pdf = FPDF()
pdf.add_page()

# Add font (must have in directory)
pdf.add_font('Lato Regular', '', os.path.join(os.getcwd(), 'Lato-Regular.ttf'), uni=True)

# Title
pdf.set_font("Lato Regular", size=20)
pdf.cell(200, 5, txt="Match Report Summary", ln=True, align='C')
pdf.ln(5)

# Match players and score
pdf.set_font_size(size=14)
pdf.cell(200, 5, txt=f"{player_name} ({client_team}) (w) v. ({opponent_name}) ({opponent_team})", ln=True, align='C')
pdf.cell(200, 10, txt="0-0 0-0 0-0", ln=True, align='C')
pdf.ln(10)

# Set up column widths and heights for alignment
column_width = 90
line_height = 7

# # Left Side - Returns
# pdf.set_font_size(size=14)
# pdf.cell(column_width, line_height, txt="Returns", ln=False, align='L')

# pdf.set_font("Arial", size=18)
# pdf.cell(column_width, line_height, txt="Errors", ln=True, align='L')
# pdf.ln(5)

# # Returns Section (Left Side)
# pdf.set_font("Arial", size=11)

# # Total Return Stats
# pdf.cell(column_width, line_height, txt=f"Total Return Made: {returnMadePercentage*100:.2f}% ({total_return})", ln=False, align='L')
# pdf.cell(column_width, line_height, txt=f"Total: {total_error_counts}", ln=True, align='L')

# pdf.cell(column_width, line_height, txt=f"Total Return Won: {returnWonByPlayer1Percentage:.2f}% ({returnWonByPlayer1})", ln=False, align='L')
# pdf.cell(column_width, line_height, txt=f"Forehand errors ({(forehand_counts/total_error_counts)*100:.2f}%):", ln=True, align='L')

# # Deuce and Ad Return Stats
# pdf.cell(column_width, line_height, txt=f"Deuce Return Made: {deuceReturnMadePercentage:.2f}% ({count_deuce_forehand_made})", ln=False, align='L')
# pdf.cell(column_width, line_height, txt=f"Net: {forehand_error_types_df.loc['Net', 'Count']}", ln=True, align='L')

# pdf.cell(column_width, line_height, txt=f"Deuce Return Won: {returnWonByPlayer1Percentage:.2f}% ({count_deuce_forehand_error})", ln=False, align='L')
# pdf.cell(column_width, line_height, txt=f"Long: {forehand_error_types_df.loc['Long', 'Count']}", ln=True, align='L')

# pdf.cell(column_width, line_height, txt="  Forehand Return:", ln=False, align='L')
# pdf.cell(column_width, line_height, txt=f"Wide Right: {forehand_error_types_df.loc['Wide Right', 'Count']}", ln=True, align='L')
# pdf.cell(column_width, line_height, txt="    Made:   | Error:", ln=False, align='L')
# pdf.cell(column_width, line_height, txt=f"Backhand errors ({(backhand_counts/total_error_counts)*100:.2f}%):", ln=True, align='L')

# pdf.cell(column_width, line_height, txt="  Backhand Return:", ln=False, align='L')
# pdf.cell(column_width, line_height, txt="Net: " + str(backhand_error_types_df.loc['Net', 'Count']), ln=True, align='L')
# pdf.cell(column_width, line_height, txt="    Made:   | Error:", ln=False, align='L')
# pdf.cell(column_width, line_height, txt="Crosscourt: ", ln=True, align='L')

# pdf.cell(column_width, line_height, txt=f"Ad Return Made: {adReturnMadePercentage:.2f}% ({count_deuce_backhand_made})", ln=False, align='L')
# pdf.cell(column_width, line_height, txt="Down the Line: ", ln=True, align='L')

# pdf.cell(column_width, line_height, txt=f"Ad Return Won: {returnWonByPlayer1Percentage:.2f}% ({count_deuce_backhand_error})", ln=False, align='L')
# pdf.cell(column_width, line_height, txt="Long: ", ln=True, align='L')

# pdf.cell(column_width, line_height, txt="  Forehand Return:", ln=False, align='L')
# pdf.cell(column_width, line_height, txt="Crosscourt: ", ln=True, align='L')
# pdf.cell(column_width, line_height, txt="    Made:   | Error:", ln=False, align='L')
# pdf.cell(column_width, line_height, txt="Down the Line: ", ln=True, align='L')

# pdf.cell(column_width, line_height, txt="  Backhand Return:", ln=False, align='L')
# pdf.cell(column_width, line_height, txt="Wide Right: ", ln=True, align='L')
# pdf.cell(column_width, line_height, txt="    Made:   | Error:", ln=False, align='L')
# pdf.cell(column_width, line_height, txt="Wide Left: ", ln=True, align='L')

# pdf.cell(column_width, line_height, txt="Down the Line: ", ln=False, align='L')
# pdf.ln(10)

# # Right Side - Errors
# pdf.set_font("Arial", size=11)
# pdf.cell(column_width, line_height, txt="Net Points", ln=False, align='L')
# pdf.ln(5)

# # Total Net Points
# pdf.cell(column_width, line_height, txt=f"Total Net Points for {player_name}: {total_at_net_player1}", ln=False, align='L')
# pdf.cell(column_width, line_height, txt=f"Percentage of Net Points for {player_name}: {percentage_at_net_player1:.2f}%", ln=True, align='L')

# pdf.cell(column_width, line_height, txt=f"Total Net Points won by {player_name}: {at_net_player1_and_won_by_player1}", ln=False, align='L')
# pdf.cell(column_width, line_height, txt=f"Percentage of Net Points won by {player_name}: {percentage_at_net_player1_and_won_by_player1:.2f}%", ln=True, align='L')
# pdf.ln(5)

# Save PDF based on players' names
pdf_name = f"{player_name}_vs_{opponent_name}_match_report.pdf"
pdf.output(f"{pdf_name}")

print(f"PDF generated: {pdf_name}")

RuntimeError: TTF Font file not found: /Users/cjgimena/Desktop/Lato-Regular.ttf